# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: esriPBuffer/graph/AddConstraintRulesRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from esriPBuffer.graph import (
    DataModelTypes_pb2 as esriPBuffer_dot_graph_dot_DataModelTypes__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n1esriPBuffer/graph/AddConstraintRulesRequest.proto\x12\x11\x65sriPBuffer.graph\x1a&esriPBuffer/graph/DataModelTypes.proto"]\n\x1eGraphConstraintRuleAddsRequest\x12;\n\x10\x63onstraint_rules\x18\x01 \x03(\x0b\x32!.esriPBuffer.graph.ConstraintRuleB%\n\x1e\x63om.esri.arcgis.protobuf.graphH\x03\xf8\x01\x01\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "esriPBuffer.graph.AddConstraintRulesRequest_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n\036com.esri.arcgis.protobuf.graphH\003\370\001\001"
    )
    _GRAPHCONSTRAINTRULEADDSREQUEST._serialized_start = 112
    _GRAPHCONSTRAINTRULEADDSREQUEST._serialized_end = 205
# @@protoc_insertion_point(module_scope)
