# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: esriPBuffer/graph/AddIndexesRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from esriPBuffer import EsriTypes_pb2 as esriPBuffer_dot_EsriTypes__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n)esriPBuffer/graph/AddIndexesRequest.proto\x12\x11\x65sriPBuffer.graph\x1a\x1b\x65sriPBuffer/EsriTypes.proto"Y\n\x1dGraphPropertyIndexAddsRequest\x12\x38\n\rfield_indexes\x18\x01 \x03(\x0b\x32!.esriPBuffer.EsriTypes.FieldIndexB%\n\x1e\x63om.esri.arcgis.protobuf.graphH\x03\xf8\x01\x01\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "esriPBuffer.graph.AddIndexesRequest_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n\036com.esri.arcgis.protobuf.graphH\003\370\001\001"
    )
    _GRAPHPROPERTYINDEXADDSREQUEST._serialized_start = 93
    _GRAPHPROPERTYINDEXADDSREQUEST._serialized_end = 182
# @@protoc_insertion_point(module_scope)
