# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: esriPBuffer/graph/AddIndexesResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from esriPBuffer.graph import (
    EsriGraphTypes_pb2 as esriPBuffer_dot_graph_dot_EsriGraphTypes__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n*esriPBuffer/graph/AddIndexesResponse.proto\x12\x11\x65sriPBuffer.graph\x1a&esriPBuffer/graph/EsriGraphTypes.proto\"T\n\x1bGraphPropertyIndexAddResult\x12\x0c\n\x04name\x18\x01 \x01(\t\x12'\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x18.esriPBuffer.graph.Error\"\x94\x01\n\x1eGraphPropertyIndexAddsResponse\x12'\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x18.esriPBuffer.graph.Error\x12I\n\x11index_add_results\x18\x02 \x03(\x0b\x32..esriPBuffer.graph.GraphPropertyIndexAddResultB%\n\x1e\x63om.esri.arcgis.protobuf.graphH\x03\xf8\x01\x01\x62\x06proto3"
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "esriPBuffer.graph.AddIndexesResponse_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n\036com.esri.arcgis.protobuf.graphH\003\370\001\001"
    )
    _GRAPHPROPERTYINDEXADDRESULT._serialized_start = 105
    _GRAPHPROPERTYINDEXADDRESULT._serialized_end = 189
    _GRAPHPROPERTYINDEXADDSRESPONSE._serialized_start = 192
    _GRAPHPROPERTYINDEXADDSRESPONSE._serialized_end = 340
# @@protoc_insertion_point(module_scope)
