# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: esriPBuffer/graph/DeleteFieldRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n*esriPBuffer/graph/DeleteFieldRequest.proto\x12\x11\x65sriPBuffer.graph"*\n\x1aGraphPropertyDeleteRequest\x12\x0c\n\x04name\x18\x01 \x01(\tB%\n\x1e\x63om.esri.arcgis.protobuf.graphH\x03\xf8\x01\x01\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "esriPBuffer.graph.DeleteFieldRequest_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n\036com.esri.arcgis.protobuf.graphH\003\370\001\001"
    )
    _GRAPHPROPERTYDELETEREQUEST._serialized_start = 65
    _GRAPHPROPERTYDELETEREQUEST._serialized_end = 107
# @@protoc_insertion_point(module_scope)
