# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: esriPBuffer/graph/GraphObjectIdentifierSet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from esriPBuffer.graph import (
    EsriGraphTypes_pb2 as esriPBuffer_dot_graph_dot_EsriGraphTypes__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n0esriPBuffer/graph/GraphObjectIdentifierSet.proto\x12\x11\x65sriPBuffer.graph\x1a&esriPBuffer/graph/EsriGraphTypes.proto"^\n\x18GraphObjectIdentifierSet\x12\x31\n\x08id_array\x18\x01 \x01(\x0b\x32\x1d.esriPBuffer.graph.ArrayValueH\x00\x42\x0f\n\rid_array_typeB\x1f\n\x18\x63om.esri.arcgis.protobufH\x03\xf8\x01\x01\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "esriPBuffer.graph.GraphObjectIdentifierSet_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"\n\030com.esri.arcgis.protobufH\003\370\001\001"
    _GRAPHOBJECTIDENTIFIERSET._serialized_start = 111
    _GRAPHOBJECTIDENTIFIERSET._serialized_end = 205
# @@protoc_insertion_point(module_scope)
