# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: esriPBuffer/graph/QueryResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from esriPBuffer import EsriTypes_pb2 as esriPBuffer_dot_EsriTypes__pb2
from esriPBuffer.graph import (
    EsriGraphTypes_pb2 as esriPBuffer_dot_graph_dot_EsriGraphTypes__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n%esriPBuffer/graph/QueryResponse.proto\x12\x11\x65sriPBuffer.graph\x1a\x1b\x65sriPBuffer/EsriTypes.proto\x1a&esriPBuffer/graph/EsriGraphTypes.proto\"\xf5\x01\n\x16GraphQueryResultHeader\x12\x1c\n\x14\x64\x61ta_model_timestamp\x18\x01 \x01(\x04\x12/\n\ttransform\x18\x02 \x01(\x0b\x32\x1c.esriPBuffer.graph.Transform\x12'\n\x05\x65rror\x18\x03 \x01(\x0b\x32\x18.esriPBuffer.graph.Error\x12\x13\n\x0b\x66ield_names\x18\x04 \x03(\t\x12\x19\n\x11\x63ompressed_frames\x18\x05 \x01(\x08\x12\x33\n\x02sr\x18\x06 \x01(\x0b\x32'.esriPBuffer.EsriTypes.SpatialReference\"<\n\rGraphQueryRow\x12+\n\x06values\x18\x01 \x03(\x0b\x32\x1b.esriPBuffer.graph.AnyValue\"\x91\x01\n\x15GraphQueryResultFrame\x12'\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x18.esriPBuffer.graph.Error\x12.\n\x04rows\x18\x02 \x03(\x0b\x32 .esriPBuffer.graph.GraphQueryRow\x12\x1f\n\x17\x65xceeded_transfer_limit\x18\x03 \x01(\x08\x42%\n\x1e\x63om.esri.arcgis.protobuf.graphH\x03\xf8\x01\x01\x62\x06proto3"
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "esriPBuffer.graph.QueryResponse_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n\036com.esri.arcgis.protobuf.graphH\003\370\001\001"
    )
    _GRAPHQUERYRESULTHEADER._serialized_start = 130
    _GRAPHQUERYRESULTHEADER._serialized_end = 375
    _GRAPHQUERYROW._serialized_start = 377
    _GRAPHQUERYROW._serialized_end = 437
    _GRAPHQUERYRESULTFRAME._serialized_start = 440
    _GRAPHQUERYRESULTFRAME._serialized_end = 585
# @@protoc_insertion_point(module_scope)
