# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: esriPBuffer/graph/QueryDataModelResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from esriPBuffer import EsriTypes_pb2 as esriPBuffer_dot_EsriTypes__pb2
from esriPBuffer.graph import (
    DataModelTypes_pb2 as esriPBuffer_dot_graph_dot_DataModelTypes__pb2,
)
from esriPBuffer.graph import (
    SearchTypes_pb2 as esriPBuffer_dot_graph_dot_SearchTypes__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n.esriPBuffer/graph/QueryDataModelResponse.proto\x12\x11\x65sriPBuffer.graph\x1a\x1b\x65sriPBuffer/EsriTypes.proto\x1a&esriPBuffer/graph/DataModelTypes.proto\x1a#esriPBuffer/graph/SearchTypes.proto\"\x91\x07\n\x0eGraphDataModel\x12\x1c\n\x14\x64\x61ta_model_timestamp\x18\x01 \x01(\x04\x12\x42\n\x11spatial_reference\x18\x02 \x01(\x0b\x32'.esriPBuffer.EsriTypes.SpatialReference\x12.\n\x07\x64omains\x18\x03 \x03(\x0b\x32\x1d.esriPBuffer.EsriTypes.Domain\x12\x33\n\x0c\x65ntity_types\x18\x04 \x03(\x0b\x32\x1d.esriPBuffer.graph.EntityType\x12?\n\x12relationship_types\x18\x05 \x03(\x0b\x32#.esriPBuffer.graph.RelationshipType\x12\x38\n\x11meta_entity_types\x18\x11 \x03(\x0b\x32\x1d.esriPBuffer.graph.EntityType\x12\x0e\n\x06strict\x18\x06 \x01(\x08\x12\x19\n\x11objectid_property\x18\x07 \x01(\t\x12\x19\n\x11globalid_property\x18\x08 \x01(\t\x12\x36\n\x0esearch_indexes\x18\x0e \x03(\x0b\x32\x1e.esriPBuffer.graph.SearchIndex\x12:\n\x0fidentifier_info\x18\x0f \x01(\x0b\x32!.esriPBuffer.graph.IdentifierInfo\x12\x1b\n\x13\x61rcgis_managed_data\x18\x10 \x01(\x08\x12T\n\x1dprovenance_source_type_values\x18\x12 \x01(\x0b\x32-.esriPBuffer.graph.ProvenanceSourceTypeValues\x12;\n\x10\x63onstraint_rules\x18\x13 \x03(\x0b\x32!.esriPBuffer.graph.ConstraintRule\x12\x43\n\x14\x65\x64itor_tracking_info\x18\x14 \x01(\x0b\x32%.esriPBuffer.graph.EditorTrackingInfoJ\x04\x08\t\x10\nJ\x04\x08\n\x10\x0bJ\x04\x08\x0b\x10\x0cJ\x04\x08\x0c\x10\rJ\x04\x08\r\x10\x0eR\x1forigin_entity_globalid_propertyR\x1d\x64\x65st_entity_globalid_propertyR\x14\x64oc_entity_type_infoR\x1aprov_meta_entity_type_infoB%\n\x1e\x63om.esri.arcgis.protobuf.graphH\x03\xf8\x01\x01\x62\x06proto3"
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "esriPBuffer.graph.QueryDataModelResponse_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n\036com.esri.arcgis.protobuf.graphH\003\370\001\001"
    )
    _GRAPHDATAMODEL._serialized_start = 176
    _GRAPHDATAMODEL._serialized_end = 1089
# @@protoc_insertion_point(module_scope)
