# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: esriPBuffer/graph/QueryTypes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n"esriPBuffer/graph/QueryTypes.proto\x12\x11\x65sriPBuffer.graph*r\n\x15TimestampOffsetFormat\x12\x16\n\x12TS_FORMAT_EPOCH_MS\x10\x00\x12"\n\x1eTS_FORMAT_DATE_TIME_COMPONENTS\x10\x01\x12\x1d\n\x19TS_FORMAT_ISO_8601_STRING\x10\x02*|\n\x0e\x44\x61teOnlyFormat\x12#\n\x1f\x44\x41TE_FORMAT_DATE_ONLY_EPOCH_DAY\x10\x00\x12$\n DATE_FORMAT_DATE_ONLY_COMPONENTS\x10\x01\x12\x1f\n\x1b\x44\x41TE_FORMAT_ISO_8601_STRING\x10\x02*|\n\x0eTimeOnlyFormat\x12#\n\x1fTIME_FORMAT_MILLISECONDS_OF_DAY\x10\x00\x12$\n TIME_FORMAT_TIME_ONLY_COMPONENTS\x10\x01\x12\x1f\n\x1bTIME_FORMAT_ISO_8601_STRING\x10\x02*^\n\x0e\x44urationFormat\x12\'\n#DURATION_FORMAT_DURATION_COMPONENTS\x10\x00\x12#\n\x1f\x44URATION_FORMAT_ISO_8601_STRING\x10\x01\x42%\n\x1e\x63om.esri.arcgis.protobuf.graphH\x03\xf8\x01\x01\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "esriPBuffer.graph.QueryTypes_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n\036com.esri.arcgis.protobuf.graphH\003\370\001\001"
    )
    _TIMESTAMPOFFSETFORMAT._serialized_start = 57
    _TIMESTAMPOFFSETFORMAT._serialized_end = 171
    _DATEONLYFORMAT._serialized_start = 173
    _DATEONLYFORMAT._serialized_end = 297
    _TIMEONLYFORMAT._serialized_start = 299
    _TIMEONLYFORMAT._serialized_end = 423
    _DURATIONFORMAT._serialized_start = 425
    _DURATIONFORMAT._serialized_end = 519
# @@protoc_insertion_point(module_scope)
