# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: esriPBuffer/graph/QueryRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from esriPBuffer import EsriTypes_pb2 as esriPBuffer_dot_EsriTypes__pb2
from esriPBuffer.graph import (
    EsriGraphTypes_pb2 as esriPBuffer_dot_graph_dot_EsriGraphTypes__pb2,
)
from esriPBuffer.graph import (
    QueryTypes_pb2 as esriPBuffer_dot_graph_dot_QueryTypes__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n$esriPBuffer/graph/QueryRequest.proto\x12\x11\x65sriPBuffer.graph\x1a\x1b\x65sriPBuffer/EsriTypes.proto\x1a&esriPBuffer/graph/EsriGraphTypes.proto\x1a\"esriPBuffer/graph/QueryTypes.proto\"\xf3\x07\n\x11GraphQueryRequest\x12\x19\n\x11open_cypher_query\x18\x01 \x01(\t\x12H\n\nparameters\x18\x02 \x03(\x0b\x32\x34.esriPBuffer.graph.GraphQueryRequest.ParametersEntry\x12\x44\n\x10\x66\x65\x61ture_encoding\x18\x03 \x01(\x0e\x32*.esriPBuffer.EsriTypes.esriFeatureEncoding\x12\x37\n\x06out_sr\x18\x04 \x01(\x0b\x32'.esriPBuffer.EsriTypes.SpatialReference\x12H\n\x14\x64\x61tum_transformation\x18\x05 \x01(\x0b\x32*.esriPBuffer.EsriTypes.DatumTransformation\x12\x1c\n\x14\x61pply_vcs_projection\x18\x06 \x01(\x08\x12J\n\x17quantization_parameters\x18\x07 \x01(\x0b\x32).esriPBuffer.graph.QuantizationParameters\x12\x35\n\x0finput_transform\x18\x08 \x01(\x0b\x32\x1c.esriPBuffer.graph.Transform\x12\x36\n\x05in_sr\x18\x0f \x01(\x0b\x32'.esriPBuffer.EsriTypes.SpatialReference\x12\x42\n\x13provenance_behavior\x18\t \x01(\x0e\x32%.esriPBuffer.graph.ProvenanceBehavior\x12\x32\n\rout_time_zone\x18\x0b \x01(\x0b\x32\x1b.esriPBuffer.graph.TimeZone\x12M\n\x1bout_timestamp_offset_format\x18\n \x01(\x0e\x32(.esriPBuffer.graph.TimestampOffsetFormat\x12?\n\x14out_date_only_format\x18\x0c \x01(\x0e\x32!.esriPBuffer.graph.DateOnlyFormat\x12?\n\x14out_time_only_format\x18\r \x01(\x0e\x32!.esriPBuffer.graph.TimeOnlyFormat\x12>\n\x13out_duration_format\x18\x0e \x01(\x0e\x32!.esriPBuffer.graph.DurationFormat\x1aN\n\x0fParametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12*\n\x05value\x18\x02 \x01(\x0b\x32\x1b.esriPBuffer.graph.AnyValue:\x02\x38\x01*.\n\x12ProvenanceBehavior\x12\x0b\n\x07\x45XCLUDE\x10\x00\x12\x0b\n\x07INCLUDE\x10\x01\x42%\n\x1e\x63om.esri.arcgis.protobuf.graphH\x03\xf8\x01\x01\x62\x06proto3"
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "esriPBuffer.graph.QueryRequest_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n\036com.esri.arcgis.protobuf.graphH\003\370\001\001"
    )
    _GRAPHQUERYREQUEST_PARAMETERSENTRY._options = None
    _GRAPHQUERYREQUEST_PARAMETERSENTRY._serialized_options = b"8\001"
    _PROVENANCEBEHAVIOR._serialized_start = 1178
    _PROVENANCEBEHAVIOR._serialized_end = 1224
    _GRAPHQUERYREQUEST._serialized_start = 165
    _GRAPHQUERYREQUEST._serialized_end = 1176
    _GRAPHQUERYREQUEST_PARAMETERSENTRY._serialized_start = 1098
    _GRAPHQUERYREQUEST_PARAMETERSENTRY._serialized_end = 1176
# @@protoc_insertion_point(module_scope)
