# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: esriPBuffer/graph/SearchTypes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from esriPBuffer.graph import (
    EsriGraphTypes_pb2 as esriPBuffer_dot_graph_dot_EsriGraphTypes__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n#esriPBuffer/graph/SearchTypes.proto\x12\x11\x65sriPBuffer.graph\x1a&esriPBuffer/graph/EsriGraphTypes.proto"\x1e\n\x0eSearchAnalyzer\x12\x0c\n\x04name\x18\x01 \x01(\t"/\n\x15SearchIndexProperties\x12\x16\n\x0eproperty_names\x18\x01 \x03(\t"\xcb\x02\n\x0bSearchIndex\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x44\n\x12supported_category\x18\x02 \x01(\x0e\x32(.esriPBuffer.graph.esriNamedTypeCategory\x12\x34\n\tanalyzers\x18\x03 \x03(\x0b\x32!.esriPBuffer.graph.SearchAnalyzer\x12O\n\x11search_properties\x18\x04 \x03(\x0b\x32\x34.esriPBuffer.graph.SearchIndex.SearchPropertiesEntry\x1a\x61\n\x15SearchPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x37\n\x05value\x18\x02 \x01(\x0b\x32(.esriPBuffer.graph.SearchIndexProperties:\x02\x38\x01\x42%\n\x1e\x63om.esri.arcgis.protobuf.graphH\x03\xf8\x01\x01\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "esriPBuffer.graph.SearchTypes_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n\036com.esri.arcgis.protobuf.graphH\003\370\001\001"
    )
    _SEARCHINDEX_SEARCHPROPERTIESENTRY._options = None
    _SEARCHINDEX_SEARCHPROPERTIESENTRY._serialized_options = b"8\001"
    _SEARCHANALYZER._serialized_start = 98
    _SEARCHANALYZER._serialized_end = 128
    _SEARCHINDEXPROPERTIES._serialized_start = 130
    _SEARCHINDEXPROPERTIES._serialized_end = 177
    _SEARCHINDEX._serialized_start = 180
    _SEARCHINDEX._serialized_end = 511
    _SEARCHINDEX_SEARCHPROPERTIESENTRY._serialized_start = 414
    _SEARCHINDEX_SEARCHPROPERTIESENTRY._serialized_end = 511
# @@protoc_insertion_point(module_scope)
