# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: esriPBuffer/graph/SyncDataModelResponse.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from esriPBuffer.graph import (
    EsriGraphTypes_pb2 as esriPBuffer_dot_graph_dot_EsriGraphTypes__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n-esriPBuffer/graph/SyncDataModelResponse.proto\x12\x11\x65sriPBuffer.graph\x1a&esriPBuffer/graph/EsriGraphTypes.proto\"\xed\x01\n\x15SyncDataModelResponse\x12'\n\x05\x65rror\x18\x01 \x01(\x0b\x32\x18.esriPBuffer.graph.Error\x12*\n\x08warnings\x18\x04 \x03(\x0b\x32\x18.esriPBuffer.graph.Error\x12G\n\x17named_type_sync_results\x18\x02 \x03(\x0b\x32&.esriPBuffer.graph.SyncDataModelResult\x12\x18\n\x10\x61sync_status_url\x18\x03 \x01(\t\x12\x1c\n\x14\x64\x61ta_model_timestamp\x18\x05 \x01(\x04\"|\n\x13SyncDataModelResult\x12\x10\n\x08typeName\x18\x01 \x01(\t\x12'\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x18.esriPBuffer.graph.Error\x12*\n\x08warnings\x18\x03 \x03(\x0b\x32\x18.esriPBuffer.graph.ErrorB%\n\x1e\x63om.esri.arcgis.protobuf.graphH\x03\xf8\x01\x01\x62\x06proto3"
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "esriPBuffer.graph.SyncDataModelResponse_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n\036com.esri.arcgis.protobuf.graphH\003\370\001\001"
    )
    _SYNCDATAMODELRESPONSE._serialized_start = 109
    _SYNCDATAMODELRESPONSE._serialized_end = 346
    _SYNCDATAMODELRESULT._serialized_start = 348
    _SYNCDATAMODELRESULT._serialized_end = 472
# @@protoc_insertion_point(module_scope)
