# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: esriPBuffer/graph/UpdateFieldRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from esriPBuffer.graph import (
    DataModelTypes_pb2 as esriPBuffer_dot_graph_dot_DataModelTypes__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n*esriPBuffer/graph/UpdateFieldRequest.proto\x12\x11\x65sriPBuffer.graph\x1a&esriPBuffer/graph/DataModelTypes.proto"\xd4\x02\n\x11GraphPropertyMask\x12\x13\n\x0bupdate_name\x18\x01 \x01(\x08\x12\x14\n\x0cupdate_alias\x18\x02 \x01(\x08\x12\x19\n\x11update_field_type\x18\x03 \x01(\x08\x12\x1c\n\x14update_geometry_type\x18\x04 \x01(\x08\x12\x1c\n\x14update_default_value\x18\x05 \x01(\x08\x12\x17\n\x0fupdate_nullable\x18\x06 \x01(\x08\x12\x17\n\x0fupdate_editable\x18\x07 \x01(\x08\x12\x16\n\x0eupdate_visible\x18\x08 \x01(\x08\x12\x17\n\x0fupdate_required\x18\t \x01(\x08\x12\x15\n\rupdate_domain\x18\n \x01(\x08\x12\x14\n\x0cupdate_has_z\x18\x0c \x01(\x08\x12\x14\n\x0cupdate_has_m\x18\r \x01(\x08J\x04\x08\x0e\x10\x0fR\x11update_searchable"\xa1\x01\n\x1aGraphPropertyUpdateRequest\x12\x32\n\x04mask\x18\x01 \x01(\x0b\x32$.esriPBuffer.graph.GraphPropertyMask\x12\x38\n\x0egraph_property\x18\x02 \x01(\x0b\x32 .esriPBuffer.graph.GraphProperty\x12\x15\n\rproperty_name\x18\x03 \x01(\tB%\n\x1e\x63om.esri.arcgis.protobuf.graphH\x03\xf8\x01\x01\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "esriPBuffer.graph.UpdateFieldRequest_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n\036com.esri.arcgis.protobuf.graphH\003\370\001\001"
    )
    _GRAPHPROPERTYMASK._serialized_start = 106
    _GRAPHPROPERTYMASK._serialized_end = 446
    _GRAPHPROPERTYUPDATEREQUEST._serialized_start = 449
    _GRAPHPROPERTYUPDATEREQUEST._serialized_end = 610
# @@protoc_insertion_point(module_scope)
