# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: esriPBuffer/graph/UpdateConstraintRulesRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from esriPBuffer.graph import (
    DataModelTypes_pb2 as esriPBuffer_dot_graph_dot_DataModelTypes__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n4esriPBuffer/graph/UpdateConstraintRulesRequest.proto\x12\x11\x65sriPBuffer.graph\x1a&esriPBuffer/graph/DataModelTypes.proto"X\n\x12\x43onstraintRuleMask\x12\x13\n\x0bupdate_name\x18\x01 \x01(\x08\x12\x14\n\x0cupdate_alias\x18\x02 \x01(\x08\x12\x17\n\x0fupdate_disabled\x18\x03 \x01(\x08"L\n\x15UpdateSetOfNamedTypes\x12\x17\n\x0f\x61\x64\x64_named_types\x18\x01 \x03(\t\x12\x1a\n\x12remove_named_types\x18\x02 \x03(\t"\x94\x02\n$GraphRelationshipExclusionRuleUpdate\x12L\n\x1aupdate_origin_entity_types\x18\x01 \x01(\x0b\x32(.esriPBuffer.graph.UpdateSetOfNamedTypes\x12K\n\x19update_relationship_types\x18\x02 \x01(\x0b\x32(.esriPBuffer.graph.UpdateSetOfNamedTypes\x12Q\n\x1fupdate_destination_entity_types\x18\x03 \x01(\x0b\x32(.esriPBuffer.graph.UpdateSetOfNamedTypes"\xa5\x02\n\x19GraphConstraintRuleUpdate\x12\x11\n\trule_name\x18\x01 \x01(\t\x12\x33\n\x04mask\x18\x02 \x01(\x0b\x32%.esriPBuffer.graph.ConstraintRuleMask\x12:\n\x0f\x63onstraint_rule\x18\x03 \x01(\x0b\x32!.esriPBuffer.graph.ConstraintRule\x12\x65\n"relationship_exclusion_rule_update\x18\x04 \x01(\x0b\x32\x37.esriPBuffer.graph.GraphRelationshipExclusionRuleUpdateH\x00\x42\x1d\n\x1bupdate_constraint_rule_type"r\n!GraphConstraintRuleUpdatesRequest\x12M\n\x17\x63onstraint_rule_updates\x18\x01 \x03(\x0b\x32,.esriPBuffer.graph.GraphConstraintRuleUpdateB%\n\x1e\x63om.esri.arcgis.protobuf.graphH\x03\xf8\x01\x01\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "esriPBuffer.graph.UpdateConstraintRulesRequest_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n\036com.esri.arcgis.protobuf.graphH\003\370\001\001"
    )
    _CONSTRAINTRULEMASK._serialized_start = 115
    _CONSTRAINTRULEMASK._serialized_end = 203
    _UPDATESETOFNAMEDTYPES._serialized_start = 205
    _UPDATESETOFNAMEDTYPES._serialized_end = 281
    _GRAPHRELATIONSHIPEXCLUSIONRULEUPDATE._serialized_start = 284
    _GRAPHRELATIONSHIPEXCLUSIONRULEUPDATE._serialized_end = 560
    _GRAPHCONSTRAINTRULEUPDATE._serialized_start = 563
    _GRAPHCONSTRAINTRULEUPDATE._serialized_end = 856
    _GRAPHCONSTRAINTRULEUPDATESREQUEST._serialized_start = 858
    _GRAPHCONSTRAINTRULEUPDATESREQUEST._serialized_end = 972
# @@protoc_insertion_point(module_scope)
