# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: esriPBuffer/graph/UpdateSearchIndexRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from esriPBuffer.graph import (
    SearchTypes_pb2 as esriPBuffer_dot_graph_dot_SearchTypes__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n0esriPBuffer/graph/UpdateSearchIndexRequest.proto\x12\x11\x65sriPBuffer.graph\x1a#esriPBuffer/graph/SearchTypes.proto"\xc8\x03\n\x1dGraphUpdateSearchIndexRequest\x12h\n\x15\x61\x64\x64_search_properties\x18\x01 \x03(\x0b\x32I.esriPBuffer.graph.GraphUpdateSearchIndexRequest.AddSearchPropertiesEntry\x12n\n\x18\x64\x65lete_search_properties\x18\x02 \x03(\x0b\x32L.esriPBuffer.graph.GraphUpdateSearchIndexRequest.DeleteSearchPropertiesEntry\x1a\x64\n\x18\x41\x64\x64SearchPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x37\n\x05value\x18\x02 \x01(\x0b\x32(.esriPBuffer.graph.SearchIndexProperties:\x02\x38\x01\x1ag\n\x1b\x44\x65leteSearchPropertiesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x37\n\x05value\x18\x02 \x01(\x0b\x32(.esriPBuffer.graph.SearchIndexProperties:\x02\x38\x01\x42%\n\x1e\x63om.esri.arcgis.protobuf.graphH\x03\xf8\x01\x01\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "esriPBuffer.graph.UpdateSearchIndexRequest_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n\036com.esri.arcgis.protobuf.graphH\003\370\001\001"
    )
    _GRAPHUPDATESEARCHINDEXREQUEST_ADDSEARCHPROPERTIESENTRY._options = None
    _GRAPHUPDATESEARCHINDEXREQUEST_ADDSEARCHPROPERTIESENTRY._serialized_options = (
        b"8\001"
    )
    _GRAPHUPDATESEARCHINDEXREQUEST_DELETESEARCHPROPERTIESENTRY._options = None
    _GRAPHUPDATESEARCHINDEXREQUEST_DELETESEARCHPROPERTIESENTRY._serialized_options = (
        b"8\001"
    )
    _GRAPHUPDATESEARCHINDEXREQUEST._serialized_start = 109
    _GRAPHUPDATESEARCHINDEXREQUEST._serialized_end = 565
    _GRAPHUPDATESEARCHINDEXREQUEST_ADDSEARCHPROPERTIESENTRY._serialized_start = 360
    _GRAPHUPDATESEARCHINDEXREQUEST_ADDSEARCHPROPERTIESENTRY._serialized_end = 460
    _GRAPHUPDATESEARCHINDEXREQUEST_DELETESEARCHPROPERTIESENTRY._serialized_start = 462
    _GRAPHUPDATESEARCHINDEXREQUEST_DELETESEARCHPROPERTIESENTRY._serialized_end = 565
# @@protoc_insertion_point(module_scope)
