# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: esriPBuffer/graph/UpdateNamedTypeRequest.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from esriPBuffer.graph import (
    DataModelTypes_pb2 as esriPBuffer_dot_graph_dot_DataModelTypes__pb2,
)


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n.esriPBuffer/graph/UpdateNamedTypeRequest.proto\x12\x11\x65sriPBuffer.graph\x1a&esriPBuffer/graph/DataModelTypes.proto"\xe4\x01\n!GraphNamedObjectTypeUpdateRequest\x12\x41\n\rentity_update\x18\x01 \x01(\x0b\x32(.esriPBuffer.graph.GraphEntityTypeUpdateH\x00\x12M\n\x13relationship_update\x18\x02 \x01(\x0b\x32..esriPBuffer.graph.GraphRelationshipTypeUpdateH\x00\x42\x13\n\x11named_type_updateJ\x04\x08\x03\x10\x04R\x12meta_entity_update"\x86\x01\n\x13NamedObjectTypeMask\x12\x13\n\x0bupdate_name\x18\x01 \x01(\x08\x12\x14\n\x0cupdate_alias\x18\x02 \x01(\x08\x12\x13\n\x0bupdate_role\x18\x04 \x01(\x08\x12\x15\n\rupdate_strict\x18\x05 \x01(\x08J\x04\x08\x03\x10\x04R\x12\x64isplay_expression"\x81\x01\n\x15GraphEntityTypeUpdate\x12\x34\n\x04mask\x18\x01 \x01(\x0b\x32&.esriPBuffer.graph.NamedObjectTypeMask\x12\x32\n\x0b\x65ntity_type\x18\x02 \x01(\x0b\x32\x1d.esriPBuffer.graph.EntityType"\x92\x02\n\x14RelationshipTypeMask\x12\x46\n\x16named_object_type_mask\x18\x01 \x01(\x0b\x32&.esriPBuffer.graph.NamedObjectTypeMaskJ\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05J\x04\x08\x05\x10\x06J\x04\x08\x06\x10\x07J\x04\x08\x07\x10\x08R\x17\x61\x64\x64_origin_entity_typesR\x1a\x64\x65lete_origin_entity_typesR\x15\x61\x64\x64_dest_entity_typesR\x18\x64\x65lete_dest_entity_typesR\x14update_strict_originR\x12update_strict_dest"\x94\x01\n\x1bGraphRelationshipTypeUpdate\x12\x35\n\x04mask\x18\x01 \x01(\x0b\x32\'.esriPBuffer.graph.RelationshipTypeMask\x12>\n\x11relationship_type\x18\x02 \x01(\x0b\x32#.esriPBuffer.graph.RelationshipTypeB%\n\x1e\x63om.esri.arcgis.protobuf.graphH\x03\xf8\x01\x01\x62\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "esriPBuffer.graph.UpdateNamedTypeRequest_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n\036com.esri.arcgis.protobuf.graphH\003\370\001\001"
    )
    _GRAPHNAMEDOBJECTTYPEUPDATEREQUEST._serialized_start = 110
    _GRAPHNAMEDOBJECTTYPEUPDATEREQUEST._serialized_end = 338
    _NAMEDOBJECTTYPEMASK._serialized_start = 341
    _NAMEDOBJECTTYPEMASK._serialized_end = 475
    _GRAPHENTITYTYPEUPDATE._serialized_start = 478
    _GRAPHENTITYTYPEUPDATE._serialized_end = 607
    _RELATIONSHIPTYPEMASK._serialized_start = 610
    _RELATIONSHIPTYPEMASK._serialized_end = 884
    _GRAPHRELATIONSHIPTYPEUPDATE._serialized_start = 887
    _GRAPHRELATIONSHIPTYPEUPDATE._serialized_end = 1035
# @@protoc_insertion_point(module_scope)
