name: arcgis_pyapi_build
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python ~=3.13
  - pip
  - python-build
  - conda-build
  - conda-index
  - conda-package-handling
  - rattler-build
  - rattler-index
  - py-rattler
  - psutil
  - nodejs >=18,<19