name: geosaurus_dev_env
channels:
- defaults
- esri
- esri/label/jupyterlab
- esri-build
dependencies:
- python 3.11
- pip
- setuptools
# ---- arcgis ----
- azure-storage-blob <=12.9
- cachetools
- certifi
- cryptography
- dask >=2023.3.2
- geomet
- keyring>=23.3.0
- lxml
- matplotlib
- matplotlib-inline
- nbconvert
- numpy>=1.21.6,<2
- pandas >=2.0.0,<2.2.0
- pillow
- puremagic >=1.15,<2
- pyarrow >=11.0.0
- pylerc
- pyshp >=2,<3
- pyspnego >=0.8.0
# - pywin32-security
- requests >=2.30.0,<2.32.0
- requests-gssapi
- requests-kerberos
- requests-oauthlib
- requests-toolbelt
- truststore
- ujson >=3
- urllib3 >=1.26.1,<3
# ---- arcgis-mapping ----
- anywidget 0.9.10
- ipywidgets >=8.0.0
- jupyterlab >=4.0.7,<5
- pydantic >=2.4.0
# ---- arcgis-learn ----
# ONLY DEPS REQUIRED FOR BUILDING DOCS
# arcgis_learn officially requires fastchan=1.0.63, 
# using unconstrained for greater compatibility
# as this is only to build the docs locally
# docs should NOT be published from this environment
# for testing only
- fastchan::fastai 
- pytorch >=2
- timm 0.4.12.*
- torchvision >=0.15.0
# ---- sphinx/docs build ----
- alabaster <0.7.14
- jinja2 3.0.3
- sphinx 3.2.1
- sphinxcontrib-applehelp <1.0.8
- sphinxcontrib-devhelp <1.0.6
- sphinxcontrib-htmlhelp <2.0.5
- sphinxcontrib-qthelp <1.0.7
- sphinxcontrib-serializinghtml <1.1.10
# ---- etc ----
- black
- keyrings.alt
- selenium
- pip:
  # ---- sphinx/docs build ----
  - sphinx-rtd-theme==0.5.2
  # ---- automated testing ----
  - coverage
  - nose2
  - parameterized
  - unittest-xml-reporting
