name: geosaurus_dev_env
channels:
- defaults
- fastai
- pytorch
dependencies:
- ipywidgets >=7
- pandas >=1
- numpy>=1.16.2
- pip
- python=3.6
- setuptools
- widgetsnbextension >=3
- keyring
- keyrings.alt
- nbconvert
- beautifulsoup4
- requests
- requests-kerberos>=0.12.0
- requests-oauthlib>=1.2.0
- pywin32>=223
- jupyterlab
- pytest
- matplotlib
- tornado<6
- scikit-learn
- scikit-image
- keras
- selenium
- scipy
- pillow
- fastai=1.0.54
- torchvision=0.3.0
- pytorch=1.1.0
- cudatoolkit
- requests
- rtree>=0.8.3
- pip:
  - unittest-xml-reporting
  - setuptools >=38.6
  - sphinx-rtd-theme
  - pytest-blockage
  - junit2html
  - coverage
  - pytest-cov
  - requests_toolbelt>=0.9.1
  - requests_ntlm
