[workspace]
authors = ["Jay Roebuck <jroebuck@esri.com>"]
channels = ["esri-build", "esri", "main"]
channel-priority = "disabled"
name = "geosaurus"
platforms = ["win-64", "linux-64", "osx-arm64", "osx-64"]
version = "0.1.0"

[tasks]
docs = {depends-on = [{task = "_docs_html", environment = "docs"}, {task = "_docs_json", environment = "docs"}], description = "Build Sphinx docs (html and json)"}
docs-html = {depends-on = [{task = "_docs_html", environment = "docs"}], description = "Build Sphinx docs (html)"}
docs-json = {depends-on = [{task = "_docs_json", environment = "docs"}], description = "Build Sphinx docs (json)"}
"_docs_html" = "cd ./docs/api_ref && make html"
"_docs_json" = "cd ./docs/api_ref && make json"

[dependencies]
python = "~=3.13"
pip = "*"
setuptools = "*"
azure-storage-blob = "<=12.9"
cachetools = "*"
certifi = "*"
cryptography = "*"
dask = ">=2024.12.1,<2025.1.0"
gdal = ">=3.6.2,<4"
geomet = "*"
keyring = ">=23.3.0"
lxml = "*"
matplotlib = "*"
matplotlib-inline = "*"
nbconvert = "*"
networkx = ">=3.3,<4"
numpy = ">=2.2.0,<3"
pandas = ">=2.0.0,<2.3.0"
pillow = "*"
puremagic = ">=1.15,<2"
pyarrow = ">=16,<20"
pylerc = "*"
pyspnego = ">=0.8.0"
pydantic = ">=2.8.2,<3"
requests = ">=2.32.3,<3"
requests-gssapi = "*"
requests-kerberos = "*"
requests-oauthlib = "*"
requests-toolbelt = "*"
truststore = ">=0.10.0"
ujson = ">=3"
urllib3 = ">=2.1.0,<3"
websocket-client = ">=1.2.3,<2"
anywidget = "==0.9.13"
ipywidgets = ">=8.0.0"
jupyterlab = ">=4.0.7,<5"
black = "~=24.0"
"keyrings.alt" = "*"
selenium = "*"
protobuf = "*"

[target.win-64.dependencies]
pywin32-security = "*"

[pypi-dependencies]
sphinx = ">=7, <8"
sphinx-rtd-theme = ">=2, <3"
autodoc-pydantic = ">=2, <3"
coverage = "*"
nose2 = "*"
parameterized = "*"
requests-mock = "*"
unittest-xml-reporting = "*"

[feature.daily]
channels = ["https://esri-forge.python.geocloud.com"]

[feature.daily.dependencies]
arcgis = ">=2.4.2,<3"

[feature.docs]
channels = ["conda-forge"]

[feature.docs.dependencies]
# spacy does not yet support python3.13
# https://github.com/explosion/spaCy/issues/13658#issuecomment-2886370190
# docs seem to build without fastai
# fastai = {channel = "fastai"}
pytorch = {channel = "conda-forge"}
timm = {channel = "esri", version = "~=0.4.12"}
torchvision = {channel = "conda-forge"}

[environments]
daily = { features = ["daily"] }
docs = { features = ["docs"] }