import datetime
import unittest
import pandas as pd
from arcgis.gis import GIS, Item
from arcgis.features.layer import Table
from arcgis.features import FeatureLayer
from arcgis.features.summarize_data import join_features
from .config_tests import setup_profiles, stage_data
from utils.decorators import integration_test

data = [
    {
        "FID": 1,
        "NAME": "MARKET FRESH GRILL CAFE",
        "ADDR": "221 W ORANGETHORPE AVE",
        "PHONE": "(714) 528-1977",
        "DAYS": "Mon - Sun",
        "HOURS": "7 AM - 9 PM",
        "OPTIONS": "Takeout, Delivery, Drive-Thru",
        "DISCOUNTS": "(School, Fire/Police, Senior Discounts)",
        "NOTES": "*Grubhub, Postmates, Doordash",
        "DEL_OPTS": "Grubhub, Postmates, Doordash",
        "TYPE": "American",
        "WEBSITE": "https://marketfreshgrillcafe.com",
        "Doordash": " ",
        "Grubhub": "https://www.grubhub.com/restaurant/market-fresh-grill-cafe-221-w-orangethorpe-ave-placentia/1290830",
        "Postmates": "https://postmates.com/merchant/toms-place-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121824.265019992,
            "y": 4010311.1421616497,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 2,
        "NAME": "301 CAFE",
        "ADDR": "301 W SANTA FE AVE",
        "PHONE": "(714) 996-8001",
        "DAYS": "Mon - Sat",
        "HOURS": "10 AM - 9:30 PM",
        "OPTIONS": "Takeout, 3rd party Delivery",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": "Doordash",
        "TYPE": "Mexican",
        "WEBSITE": " ",
        "Doordash": "https://www.doordash.com/store/301-cafe-placentia-723324/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121629.643094601,
            "y": 4011297.297220264,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 3,
        "NAME": "Q TORTAS",
        "ADDR": "220 S BRADFORD AVE",
        "PHONE": "(714) 993-3270",
        "DAYS": "Tue - Friday, Sat - Sun",
        "HOURS": "11 AM - 8 PM, 9 AM - 8 PM",
        "OPTIONS": "Takeout",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "TYPE": "Mexican",
        "WEBSITE": " ",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121342.054302571,
            "y": 4011316.8427645396,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 4,
        "NAME": "THE WHOLE ENCHILADA",
        "ADDR": "106 E YORBA LINDA BLVD",
        "PHONE": "(714) 961-9123",
        "DAYS": "Mon - Sun",
        "HOURS": "11 AM - 8 PM",
        "OPTIONS": "Takeout, Delivery",
        "DISCOUNTS": "None",
        "NOTES": "*Doordash",
        "DEL_OPTS": "Doordash",
        "TYPE": "Mexican",
        "WEBSITE": "https://wholeenchilada.com",
        "Doordash": "https://www.doordash.com/store/the-whole-enchilada-placentia-56007/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120774.654751526,
            "y": 4013636.1349284584,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 5,
        "NAME": "AVALON BAGLES AND BURGERS",
        "ADDR": "174 E YORBA LINDA BLVD",
        "PHONE": "(714) 985-1382",
        "DAYS": "Mon - Sun",
        "HOURS": "7AM - 4 PM",
        "OPTIONS": "Takeout, 3rd party Delivery",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": "Grubhub, Doordash, Seamless",
        "TYPE": "Bagels, Burgers, Sandwiches",
        "WEBSITE": "https://avalonbagelstoburgers.com/",
        "Doordash": "https://www.doordash.com/store/avalon-bagels-to-burgers-placentia-320809/en-US",
        "Grubhub": "https://www.grubhub.com/restaurant/avalon-bagels-to-burgers---placentia-174-e-yorba-linda-blvd-placentia/553124",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120516.589507373,
            "y": 4013511.6346839233,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 6,
        "NAME": "ISE JAPANESE RESTAURANT",
        "ADDR": "1241 E YORBA LINDA BLVD",
        "PHONE": "(714) 993-6442",
        "DAYS": "Mon - Thur, Fri, Sat",
        "HOURS": "11 AM - 10 PM, 11 AM - 10:30 PM, 11:30 AM - 10 PM",
        "OPTIONS": "Takeout",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "TYPE": "Japanese",
        "WEBSITE": "https://isesushi.wordpress.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13117975.00648396,
            "y": 4013952.0928615234,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 7,
        "NAME": "COFFEE BEAN & TEA LEAF #392",
        "ADDR": "1188 E YORBA LINDA BLVD",
        "PHONE": "(310) 237-2326",
        "DAYS": "Mon - Sun",
        "HOURS": "6 AM - 6 PM",
        "OPTIONS": "Drive-Thru",
        "DISCOUNTS": "None",
        "NOTES": "657-216-5920",
        "DEL_OPTS": "Postmates",
        "TYPE": "Coffee",
        "WEBSITE": "https://coffeebean.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": "https://postmates.com/merchant/the-coffee-bean-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118132.860060971,
            "y": 4013795.8679011846,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 8,
        "NAME": "PORKY'S PIZZA",
        "ADDR": "1152 E IMPERIAL HWY",
        "PHONE": "(714) 572-1777",
        "DAYS": "Sun - Thur, Fri - Sat",
        "HOURS": "11 AM - 9 PM, 11 AM - 10 PM",
        "OPTIONS": "Takeout, Delivery",
        "DISCOUNTS": "None",
        "NOTES": "*Ubereats, Postmates, Doordash",
        "DEL_OPTS": "Ubereats, Postmates, Doordash",
        "TYPE": "Pizza",
        "WEBSITE": "https://porkyspizza.com",
        "Doordash": "https://www.doordash.com/store/porky-s-pizza-placentia-16731/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118260.5041459,
            "y": 4015977.511310816,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 9,
        "NAME": "FISH IN A BOTTLE",
        "ADDR": "1205 E IMPERIAL HWY",
        "PHONE": "(714) 528-4000",
        "DAYS": "Until this Sunday",
        "HOURS": "11:30 AM - 9:30 PM, Sat 11:30 AM -10:30, Sun 4 PM*",
        "OPTIONS": "Take-out",
        "DISCOUNTS": "None",
        "NOTES": "*Doordash, Postmates, call in orders only, Will n*",
        "DEL_OPTS": "Doordash, Postmates",
        "TYPE": "Sushi",
        "WEBSITE": "http://fish-in-a-bottle-sushi-grill.cafes-usa.com/",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": "https://postmates.com/merchant/fish-in-a-bottle-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118048.480420934,
            "y": 4015961.906490283,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 10,
        "NAME": "WINGSTOP #1553",
        "ADDR": "1093 E IMPERIAL HWY",
        "PHONE": "(714) 868-7000",
        "DAYS": "Mon - Sun",
        "HOURS": "10:30 AM - Midnight",
        "OPTIONS": "Delivery, Takeout",
        "DISCOUNTS": "Mondays & Tuesdays 60 cent boneless wings.",
        "NOTES": "*Doordash",
        "DEL_OPTS": "Doordash",
        "TYPE": "Chicken Wings",
        "WEBSITE": "https://wingstop.com",
        "Doordash": "https://www.doordash.com/store/wingstop-placentia-647491/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118439.698197426,
            "y": 4016169.0124437176,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 11,
        "NAME": "WIENERSCHNITZEL #626",
        "ADDR": "1005 E IMPERIAL HWY",
        "PHONE": "(714) 996-0570",
        "DAYS": "Mon - Sun",
        "HOURS": "10AM - 10PM",
        "OPTIONS": "Drive-Thru, 3rd party Delivery",
        "DISCOUNTS": "None",
        "NOTES": "*Ubereats. 714-996-0570",
        "DEL_OPTS": "Ubereats",
        "TYPE": "Hot dogs",
        "WEBSITE": "https://wienerschnitzel.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": "https://postmates.com/merchant/weinerschnitzel-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118485.377682252,
            "y": 4016191.4002631214,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 12,
        "NAME": "SUBWAY # 3443",
        "ADDR": "1807 E ORANGETHORPE AVE",
        "PHONE": "(714) 579-3160",
        "DAYS": "Mon - Fri",
        "HOURS": "8 AM - 4PM",
        "OPTIONS": "Takeout, 3rd party Delivery",
        "DISCOUNTS": "Website only",
        "NOTES": "*Postmates, Doordash",
        "DEL_OPTS": "Postmates, Doordash",
        "TYPE": "Sandwich",
        "WEBSITE": "https://subway.com",
        "Doordash": "https://www.doordash.com/store/subway-orange-county-placentia-57327/en-US",
        "Grubhub": " ",
        "Postmates": "https://postmates.com/merchant/subway-placentia-5",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13116301.460162882,
            "y": 4011152.5278131273,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 13,
        "NAME": "SAKE SUSHI & GRILL/JOO INC",
        "ADDR": "850 N ROSE DR",
        "PHONE": "(714) 528-7253",
        "DAYS": "Mon - Sun",
        "HOURS": "11:30 AM - 2:30 PM/5 PM - 9:30 PM (Sunday's 5 - 9*",
        "OPTIONS": "Takeout, Delivery",
        "DISCOUNTS": "Free Delivery Dinner only",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "TYPE": "Sushi",
        "WEBSITE": "https://sake-sushi-grill.cafes-usa.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": "https://postmates.com/merchant/sake-sushi-grill-placentia-59451",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118198.942123447,
            "y": 4012522.1051237006,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 14,
        "NAME": "KFC",
        "ADDR": "1404 N KRAEMER BLVD",
        "PHONE": "(562) 500-5940",
        "DAYS": "Mon - Sun",
        "HOURS": "10 AM - 10 PM varies",
        "OPTIONS": "Takeout",
        "DISCOUNTS": "None",
        "NOTES": "*Free Delivery thru KFC.com",
        "DEL_OPTS": " ",
        "TYPE": "Chicken",
        "WEBSITE": "https://kfc.com",
        "Doordash": " ",
        "Grubhub": "https://www.grubhub.com/restaurant/kfc-1404-n-kraemer-blvd-placentia/936214",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120433.63573153,
            "y": 4013632.9932656037,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 15,
        "NAME": "MCDONALD'S",
        "ADDR": "770 W CHAPMAN AVE",
        "PHONE": "(714) 630-9430",
        "DAYS": "Mon - Sun",
        "HOURS": "6 AM - 2 AM",
        "OPTIONS": "Drive-Thru",
        "DISCOUNTS": "None",
        "NOTES": "*714-577-8171. Ubereats, Doordash",
        "DEL_OPTS": "Ubereats, Doordash",
        "TYPE": "Burgers, Fast Food",
        "WEBSITE": "https://mcdonalds.com",
        "Doordash": "https://www.doordash.com/store/mcdonald-s-placentia-653621/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13122186.242973486,
            "y": 4011840.121557618,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 16,
        "NAME": "WABA GRILL #204",
        "ADDR": "720 N ROSE DR",
        "PHONE": "(714) 577-9222",
        "DAYS": "Mon - Sat, Sun",
        "HOURS": "11AM - 8 PM, 11 AM - 8 PM",
        "OPTIONS": "Takeout, Delivery",
        "DISCOUNTS": "4 Chicken Bowls for $20, Family Meal $19.99",
        "NOTES": "*Postmates, Grubhub, Doordash, Ubereats",
        "DEL_OPTS": "Postmates, Grubhub, Doordash, Ubereats",
        "TYPE": "Asian Fusion",
        "WEBSITE": "https://wabagrill.com",
        "Doordash": "https://www.doordash.com/store/waba-grill-placentia-187728/en-US",
        "Grubhub": "https://www.grubhub.com/restaurant/waba-grill-720-n-rose-dr-placentia/625459",
        "Postmates": "https://postmates.com/merchant/waba-grill-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118102.344055684,
            "y": 4012420.7617618423,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 17,
        "NAME": "MINI GOURMET",
        "ADDR": "1210 E YORBA LINDA BLVD",
        "PHONE": "(714) 524-1611",
        "DAYS": "Thur-Tue",
        "HOURS": "6:30 AM - 2 PM",
        "OPTIONS": "Takeout",
        "DISCOUNTS": "5% Discounts off total purchase",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "TYPE": "Breakfast & Brunch",
        "WEBSITE": "https://mini-gourmet-restaurant.business.site",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118016.23447817,
            "y": 4013710.0375595465,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 18,
        "NAME": "MCDONALD'S OF PLACENTIA",
        "ADDR": "164 E YORBA LINDA BLVD",
        "PHONE": "(714) 993-3121",
        "DAYS": "Mon - Sun",
        "HOURS": "5 AM - Midnight",
        "OPTIONS": "Delivery, Drive-up",
        "DISCOUNTS": "None",
        "NOTES": "*Doordash, Ubereats",
        "DEL_OPTS": "Doordash, Ubereats",
        "TYPE": "Burgers, Fast Food",
        "WEBSITE": "https://mcdonalds.com",
        "Doordash": "https://www.doordash.com/store/mcdonald-s-placentia-662251/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120507.813723624,
            "y": 4013598.500116996,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 19,
        "NAME": "TACO BELL",
        "ADDR": "1174 E YORBA LINDA BLVD",
        "PHONE": "(714) 528-3122",
        "DAYS": "Mon - Sun",
        "HOURS": "10 AM - 11 PM",
        "OPTIONS": "Drive-Thru, 3rd party Delivery",
        "DISCOUNTS": "None",
        "NOTES": "714-528-3122. Grubhub, Postmates, Ubereats, Doord*",
        "DEL_OPTS": "Grubhub, Postmates, Ubereats, Doordash",
        "TYPE": "Mexican",
        "WEBSITE": "https://locations.tacobell.com/ca/placentia/1174-yorba-linda-blvd-.html",
        "Doordash": " ",
        "Grubhub": "https://www.grubhub.com/restaurant/taco-bell-1174-e-yorba-linda-blvd-placentia/927181",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118168.328904405,
            "y": 4013789.6247696993,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 20,
        "NAME": "DUKE'S CAFE",
        "ADDR": "2099 E ORANGETHORPE AVE",
        "PHONE": "(714) 983-7056",
        "DAYS": "Mon- Sun",
        "HOURS": "7 AM - 9 PM",
        "OPTIONS": "Takeout, 3rd party Delivery",
        "DISCOUNTS": "None",
        "NOTES": "*Doordash, ChowNow",
        "DEL_OPTS": "Doordash, ChowNow",
        "TYPE": "Breakfast & Brunch, Mexican, Sandwiches",
        "WEBSITE": "https://dukescafeyl.com",
        "Doordash": "https://www.doordash.com/store/duke-s-cafe-placentia-55927/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13115541.226824583,
            "y": 4010967.5127567225,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 21,
        "NAME": "PIZZA HUT DELIVERY # 24890",
        "ADDR": "901 E YORBA LINDA BLVD UNIT A",
        "PHONE": "(714) 996-4222",
        "DAYS": "Sun - Thur, Fri- Sat",
        "HOURS": "10 AM - Midnight, 10 AM - 1 AM",
        "OPTIONS": "Pickup, Delivery",
        "DISCOUNTS": "Specials only, available online",
        "NOTES": "*Grubhub, Doordash",
        "DEL_OPTS": "Grubhub, Doordash, Pizza Hut",
        "TYPE": "Pizza",
        "WEBSITE": "https://pizzahutdelivery.com",
        "Doordash": " ",
        "Grubhub": "https://www.grubhub.com/restaurant/pizza-hut-901-e-yorba-linda-blvd-placentia/1128198",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118794.10913479,
            "y": 4014016.9734648396,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 22,
        "NAME": "JACK IN THE BOX #3253",
        "ADDR": "1097 E IMPERIAL HWY",
        "PHONE": "(714) 528-2960",
        "DAYS": "Mon - Sun",
        "HOURS": "6 AM - Midnight",
        "OPTIONS": "Takeout, Drive-Thru",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "TYPE": "Burgers, Fast Food",
        "WEBSITE": "https://jackinthebox.com",
        "Doordash": " ",
        "Grubhub": "https://www.grubhub.com/restaurant/jack-in-the-box-1097-e-imperial-hwy-placentia/669594",
        "Postmates": "https://postmates.com/merchant/jack-in-the-box-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118406.05624054,
            "y": 4016152.8211497087,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 23,
        "NAME": "DEL TACO, LLC #917",
        "ADDR": "1171 E IMPERIAL HWY",
        "PHONE": "(714) 985-9095",
        "DAYS": "Mon - Sun",
        "HOURS": "24 HR",
        "OPTIONS": "Curbside, 3rd party Delivery",
        "DISCOUNTS": "None",
        "NOTES": "Ubereats, Doordash, Grubhub, Postmates",
        "DEL_OPTS": "Ubereats, Doordash, Grubhub, Postmates",
        "TYPE": "Mexican",
        "WEBSITE": "https://deltaco.com",
        "Doordash": "https://www.doordash.com/store/del-taco-placentia-548449/en-US",
        "Grubhub": "https://www.grubhub.com/restaurant/del-taco-1171-e-imperial-highway-placentia/1027911",
        "Postmates": "https://postmates.com/merchant/del-taco-placentia-1",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118171.300098535,
            "y": 4016033.4662593096,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 24,
        "NAME": "FANTASY BURGER",
        "ADDR": "510 W CHAPMAN AVE",
        "PHONE": "(714) 223-1981",
        "DAYS": "Mon - Sun",
        "HOURS": "6 AM - 10 PM, Sun 7 AM - 10 PM",
        "OPTIONS": "Take-Out, Drive Thru, 3rd Party Delivery",
        "DISCOUNTS": "None",
        "NOTES": "*None, Phone call or walk in orders for take-out",
        "DEL_OPTS": "None",
        "TYPE": "Burgers, Fast Food",
        "WEBSITE": "https://fantasy-burger.cafes-usa.com",
        "Doordash": "https://www.doordash.com/store/fantasy-burger-placentia-18612/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121824.990080802,
            "y": 4011730.078537878,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 25,
        "NAME": "LOS GALLOS RESTAURANT",
        "ADDR": "1667 E ORANGETHORPE AVE",
        "PHONE": "(714) 579-7955",
        "DAYS": "Mon - Sun",
        "HOURS": "11 AM - 6:30 PM",
        "OPTIONS": "Takeout",
        "DISCOUNTS": "None",
        "NOTES": "*Also has been receiving fradulent phone calls fr*",
        "DEL_OPTS": "Doordash",
        "TYPE": "Mexican",
        "WEBSITE": " ",
        "Doordash": "https://www.doordash.com/store/los-gallos-placentia-682330/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13116713.940300839,
            "y": 4011162.386565792,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 26,
        "NAME": "CARL'S JR #663",
        "ADDR": "750 N ROSE DR",
        "PHONE": "(805) 672-2889",
        "DAYS": "Mon - Sun",
        "HOURS": "6 AM - 11PM",
        "OPTIONS": "Delivery, Takeout, Drive-Thru",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": "Grubhub",
        "TYPE": "Burgers, Fast Food",
        "WEBSITE": "https://carlsjr.com",
        "Doordash": " ",
        "Grubhub": "https://www.grubhub.com/restaurant/carls-jr-1285-e-imperial-hwy-placentia/1016047",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118237.315790087,
            "y": 4012395.985027623,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 27,
        "NAME": "SUBWAY 29842",
        "ADDR": "1208 E YORBA LINDA BLVD",
        "PHONE": "(714) 579-6555",
        "DAYS": "Mon - Fri, Sat - Sun",
        "HOURS": "10 AM - 7PM, 11 AM - 6:30 PM",
        "OPTIONS": "Delivery, Takeout",
        "DISCOUNTS": "None",
        "NOTES": "*Ubereats, Grubhub, Postmates, Doordash",
        "DEL_OPTS": "Ubereats, Grubhub, Postmates, Doordash",
        "TYPE": "Sandwich",
        "WEBSITE": "https://subway.com",
        "Doordash": "https://www.doordash.com/store/subway-placentia-381793/en-US",
        "Grubhub": "https://www.grubhub.com/restaurant/subway-1208-e-yorba-linda-blvd-placentia/1065086",
        "Postmates": "https://postmates.com/merchant/subway-placentia-1",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118023.658378506,
            "y": 4013710.37327354,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 28,
        "NAME": "COCINA AZTECA GRILL LLC",
        "ADDR": "111 E CHAPMAN AVE",
        "PHONE": "(714) 577-9900",
        "DAYS": "Mon - Sun",
        "HOURS": "8 AM - 8 PM",
        "OPTIONS": "Delivery, Takeout",
        "DISCOUNTS": "None",
        "NOTES": "*Ubereats, Doordash, Postmates, Online Order (Coc*",
        "DEL_OPTS": "Ubereats, Doordash, Postmates",
        "TYPE": "Mexican",
        "WEBSITE": "https://cocinaaztecagrill.com",
        "Doordash": " ",
        "Grubhub": "https://www.grubhub.com/restaurant/cocina-azteca-e-chapman-ave-old-name-111-e-chapman-ave-placentia/1939612",
        "Postmates": "https://postmates.com/merchant/cocina-azteca-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121233.98441139,
            "y": 4011666.5631723735,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 29,
        "NAME": "MOO CAFE, LLC",
        "ADDR": "118 N BRADFORD AVE",
        "PHONE": "(714) 646-9311",
        "DAYS": "Sun - Thur, Fri - Sun",
        "HOURS": "11 AM - 8 PM, 11 AM - 9 PM",
        "OPTIONS": "Takeout, Delivery",
        "DISCOUNTS": "None",
        "NOTES": "*Grubhub, Ubereats",
        "DEL_OPTS": "Grubhub, Ubereats",
        "TYPE": "Tea House",
        "WEBSITE": "https://moocafeco.com",
        "Doordash": "https://www.doordash.com/store/moo-cafe-placentia-824819/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121194.842499591,
            "y": 4011760.301052922,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 30,
        "NAME": "PHILLY'S BEST",
        "ADDR": "198 E YORBA LINDA BLVD",
        "PHONE": "(714) 996-3278",
        "DAYS": "Mon - Sat, Sun",
        "HOURS": "10 AM - 9 AM, 11 AM - 8 PM",
        "OPTIONS": "Takeout",
        "DISCOUNTS": "None",
        "NOTES": "*Doordash, Postmates",
        "DEL_OPTS": "Doordash, Postmates",
        "TYPE": "Sandwich",
        "WEBSITE": "https://eatphillysbest.com/",
        "Doordash": "https://www.doordash.com/store/philly-s-best-placentia-16702/en-US",
        "Grubhub": " ",
        "Postmates": "https://postmates.com/merchant/phillys-best-placentia-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120479.211405389,
            "y": 4013465.3630684135,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 31,
        "NAME": "CRAFTSMAN WOOD FIRED PIZZA",
        "ADDR": "148 E YORBA LINDA BLVD",
        "PHONE": "(714) 579-1777",
        "DAYS": "Mon - Sun",
        "HOURS": "4 PM - 7 PM",
        "OPTIONS": "Curbside, Delivery",
        "DISCOUNTS": " ",
        "NOTES": "*Closed but will reopen March 23. Delivery throug*",
        "DEL_OPTS": "Postmates, Slice",
        "TYPE": "Pizza",
        "WEBSITE": "https://craftsmanpizza.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": "https://postmates.com/merchant/craftsman-wood-fired-pizza-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120610.333340239,
            "y": 4013534.0243102526,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 32,
        "NAME": "DOMINO'S PIZZA #8170",
        "ADDR": "1913 N PLACENTIA AVE",
        "PHONE": "(562) 522-6925",
        "DAYS": "Sun - Thu, Fri - Sat",
        "HOURS": "10 AM - Midnight, 10 AM - 1 AM",
        "OPTIONS": "Delivery, Takout",
        "DISCOUNTS": "Specials only, available online",
        "NOTES": " ",
        "DEL_OPTS": "Dominos",
        "TYPE": "Pizza",
        "WEBSITE": "https://domino'spizza.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121534.992394976,
            "y": 4014959.5990541936,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 33,
        "NAME": "GINA MARIA'S PIZZERIA",
        "ADDR": "1525 N PLACENTIA AVE",
        "PHONE": "(714) 996-7371",
        "DAYS": "Tues - Thurs, Fri - Sat, Sun",
        "HOURS": "11 AM - 9 PM, 11 AM - 10 PM, 11 AM - 9 PM",
        "OPTIONS": "Takeout",
        "DISCOUNTS": "$12 Off 1st Order",
        "NOTES": "*Grubhub, Doordash, Seamless",
        "DEL_OPTS": "Grubhub, Doordash, Seamless",
        "TYPE": "Pizza",
        "WEBSITE": "https://myginamarias.com",
        "Doordash": "https://www.doordash.com/store/gina-maria-s-pizzeria-placentia-756799/en-US",
        "Grubhub": "https://www.grubhub.com/restaurant/gina-marias-pizzeria-1525-n-placentia-ave-placentia/1445600",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121714.55736742,
            "y": 4014210.2237393702,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 34,
        "NAME": "LITTLE CAESAR'S",
        "ADDR": "1212 E YORBA LINDA BLVD",
        "PHONE": "(909) 579-1583",
        "DAYS": "Mon - Sun",
        "HOURS": "11 AM - 10 PM",
        "OPTIONS": "Delivery, Takeout",
        "DISCOUNTS": "None",
        "NOTES": "*714-996-9600. Doordash, Postmates",
        "DEL_OPTS": "Doordash, Postmates",
        "TYPE": "Pizza",
        "WEBSITE": "https://littlecaesars.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": "https://postmates.com/merchant/little-caesars-pizza-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118008.241812466,
            "y": 4013710.5583820003,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 35,
        "NAME": "PEPZ PIZZA IN PLACENTIA",
        "ADDR": "732 N ROSE DR",
        "PHONE": "(714) 572-2100",
        "DAYS": "Mon - Sun",
        "HOURS": "11 AM - 9 PM",
        "OPTIONS": "Pickup, Delivery",
        "DISCOUNTS": "None",
        "NOTES": "*Specials, Grubhub, Chownow, Slice, Doordash",
        "DEL_OPTS": "Grubhub, Chownow, Slice, Doordash",
        "TYPE": "Pizza",
        "WEBSITE": "https://pepzpizzamenu.com",
        "Doordash": "https://www.doordash.com/store/pepz-pizza-eatery-placentia-16441/en-US",
        "Grubhub": "https://www.grubhub.com/restaurant/pepz-pizza--eatery-732-n-rose-dr-placentia/287844",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118103.270412136,
            "y": 4012442.0285473377,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 36,
        "NAME": "EVEREST CUISINE OF INDIA",
        "ADDR": "2075 E ORANGETHORPE AVE",
        "PHONE": "(714) 993-0111",
        "DAYS": "Mon - Sun",
        "HOURS": "11 AM - 3 PM, 5 Pm 10 PM",
        "OPTIONS": "Delivery, Take-Out",
        "DISCOUNTS": "None",
        "NOTES": "*Ubereats, Doordash, Grubhub, Postmates, Free del*",
        "DEL_OPTS": "Ubereats, Doordash, Grubhub, Postmates",
        "TYPE": "Indian",
        "WEBSITE": "https://everestcuisineplacentia.com",
        "Doordash": "https://www.doordash.com/store/everest-cuisine-of-india-placentia-648429/en-US",
        "Grubhub": "https://www.grubhub.com/restaurant/everest-cuisine-of-india-2075-e-orangethorpe-ave-placentia/1174860",
        "Postmates": "https://postmates.com/merchant/everest-cuisine-of-india-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13115615.374400198,
            "y": 4011083.490705672,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 37,
        "NAME": "DENNY'S #7656",
        "ADDR": "108 E ORANGETHORPE AVE",
        "PHONE": "(714) 528-1661",
        "DAYS": "Sun - Thurs, Fri - Sat",
        "HOURS": "7 AM - 10 PM, FRI/SAT 7 AM - 12 AM",
        "OPTIONS": "Delivery, Take-Out",
        "DISCOUNTS": "None",
        "NOTES": "Ubereats, Doordash, Grubhub, Postmates, Free deli*",
        "DEL_OPTS": "Ubereats, Doordash, Grubhub, Postmates, Free deli*",
        "TYPE": "American",
        "WEBSITE": "https://dennys.com",
        "Doordash": " ",
        "Grubhub": "https://www.grubhub.com/restaurant/dennys-108-e-orangethorpe-ave-placentia/668012",
        "Postmates": "https://postmates.com/merchant/dennys-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121503.825299881,
            "y": 4010286.6979383333,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 38,
        "NAME": "BROWN BAG PLUS PIZZA MAN",
        "ADDR": "350 E ORANGETHORPE AVE",
        "PHONE": "(714) 996-5670",
        "DAYS": "Mon - Sun",
        "HOURS": "11 AM - 11 PM",
        "OPTIONS": "Delivery, Takeout",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": "Grubhub, Seamless, Slice, delivery.com,",
        "TYPE": "Pizza",
        "WEBSITE": "https://pizzamanplacentia.blizzfull.com",
        "Doordash": " ",
        "Grubhub": "https://www.grubhub.com/restaurant/pizza-man-350-e-orangethorpe-ave-ste-29-placentia/157146",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120623.785165453,
            "y": 4010561.694025211,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 39,
        "NAME": "EL PUEBLITO RESTAURANT, INC",
        "ADDR": "1221 E IMPERIAL HWY",
        "PHONE": "(714) 854-7956",
        "DAYS": "Sun - Thur, Fri - Sat",
        "HOURS": "Weekdays & Sun 9 AM -  9 AM, 9 AM - 7 PM",
        "OPTIONS": "Pickup, Takeout",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "TYPE": "Mexican",
        "WEBSITE": "https://el-pueblito.cafes-usa.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118003.454789553,
            "y": 4015983.700098523,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 40,
        "NAME": "BROOKLYN PIZZA WORKS & ITALIAN RESTAURANT",
        "ADDR": "1235 E IMPERIAL HWY",
        "PHONE": "(714) 524-1260",
        "DAYS": "Tues - Sun",
        "HOURS": "11 AM - 9 PM",
        "OPTIONS": "Delivery, Takeout",
        "DISCOUNTS": "$10 Meal/per person",
        "NOTES": "*Delivery & pick up specials for pizza & pasta/Co*",
        "DEL_OPTS": "Grubhub, Seamless, Postmates, Slice",
        "TYPE": "Pizza, Italian",
        "WEBSITE": "https://www.brooklynpizzaplacentia.com/",
        "Doordash": " ",
        "Grubhub": "https://www.grubhub.com/restaurant/brooklyn-pizza-works-1235-e-imperial-hwy-placentia/557250",
        "Postmates": "https://postmates.com/merchant/brooklyn-pizza-works-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13117969.81481402,
            "y": 4016055.7807497126,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 41,
        "NAME": "YASAI JAPANESE GRILL",
        "ADDR": "139 E YORBA LINDA BLVD",
        "PHONE": "(714) 577-8349",
        "DAYS": "Mon - Sun",
        "HOURS": "11 AM - 9 PM (hours vary)",
        "OPTIONS": "Takeout only, 3rd party Delivery",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": "Doordash",
        "TYPE": "Japanese",
        "WEBSITE": "https://yasaiusa.com",
        "Doordash": "https://www.doordash.com/store/yasai-japanese-grill-placentia-16498/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120650.598306773,
            "y": 4013812.239376756,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 42,
        "NAME": "WASABI SUSHI & ROLL",
        "ADDR": "1041 E IMPERIAL HWY",
        "PHONE": "(714) 223-7878",
        "DAYS": "Fri - Sun",
        "HOURS": "12 PM - 8 PM",
        "OPTIONS": "Takeout, Delivery",
        "DISCOUNTS": "None",
        "NOTES": "*Doordash",
        "DEL_OPTS": "Doordash",
        "TYPE": "Asian Fusion",
        "WEBSITE": " ",
        "Doordash": "https://www.doordash.com/store/wasabi-sushi-roll-placentia-448827/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118402.813638357,
            "y": 4016226.8834075034,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 43,
        "NAME": "B & C BURGERS",
        "ADDR": "1868 N PLACENTIA AVE",
        "PHONE": "(714) 227-0477",
        "DAYS": "Mon - Sun",
        "HOURS": "8 AM - 8 PM",
        "OPTIONS": "Takeout, 3rd party Delivery",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": "Doordash",
        "TYPE": "Mexican",
        "WEBSITE": "https://www.bncburgers.com/",
        "Doordash": "https://www.doordash.com/store/b-c-burgers-placentia-31865/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121282.171514187,
            "y": 4014775.7417710708,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 44,
        "NAME": "MEAT UP BBQ",
        "ADDR": "1450 N KRAEMER BLVD",
        "PHONE": "(714) 983-7558",
        "DAYS": "Tue - Sun",
        "HOURS": "11 AM - 9 PM",
        "OPTIONS": "Takeout, Delivery",
        "DISCOUNTS": "FREE Delivery within 5 Miles with $50 order",
        "NOTES": "*Ubereats (Free Delivery), Doordash, Grubhub",
        "DEL_OPTS": "Ubereats, Doordash, Grubhub",
        "TYPE": "Barbecue",
        "WEBSITE": "https://meatupbbq.com",
        "Doordash": "https://www.doordash.com/store/meat-up-bbq-placentia-16344/en-US",
        "Grubhub": "https://www.grubhub.com/restaurant/meat-up-bbq-1450-n-kraemer-blvd-placentia/1465867",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120326.698656239,
            "y": 4013656.4313308746,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 45,
        "NAME": "SAIGON NOODLE HOUSE",
        "ADDR": "1486 N KRAEMER BLVD",
        "PHONE": "(714) 528-4087",
        "DAYS": "Mon - Sun",
        "HOURS": "3 PM - 7 PM (Mar. 18 - March 31)",
        "OPTIONS": " ",
        "DISCOUNTS": "None",
        "NOTES": "*Callback later after 3 pm",
        "DEL_OPTS": " ",
        "TYPE": "Vietnamese",
        "WEBSITE": " ",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120312.449413177,
            "y": 4013751.594451005,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 46,
        "NAME": "CHIPOTLE MEXICAN GRILL #3373",
        "ADDR": "1474 N KRAEMER BLVD",
        "PHONE": "(614) 318-2482",
        "DAYS": "Mon - Sun",
        "HOURS": "10:45 AM - 10 PM",
        "OPTIONS": "Takeout",
        "DISCOUNTS": "Free Delivery",
        "NOTES": "*Doordash",
        "DEL_OPTS": "Doordash, Postmates",
        "TYPE": "Mexican",
        "WEBSITE": "https://chipotle.com",
        "Doordash": "https://www.doordash.com/store/chipotle-placentia-742870/en-US",
        "Grubhub": " ",
        "Postmates": "https://postmates.com/merchant/chipotle-mexican-grill-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120437.835755944,
            "y": 4013714.0116992784,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 47,
        "NAME": "TAQUERIA DE ANDA",
        "ADDR": "602 W CHAPMAN AVE",
        "PHONE": "(714) 404-6766",
        "DAYS": "Mon - Sun",
        "HOURS": "9 AM - 9 PM",
        "OPTIONS": "Takeout, Delivery",
        "DISCOUNTS": "None",
        "NOTES": "*Doordash",
        "DEL_OPTS": "Doordash",
        "TYPE": "Mexican",
        "WEBSITE": "https://taqueriadeanda.com",
        "Doordash": "https://www.doordash.com/store/taqueria-de-anda-placentia-357761/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121900.60925604,
            "y": 4011768.6960266614,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 48,
        "NAME": "LITTLE CAESARS #5714",
        "ADDR": "630 W CHAPMAN AVE",
        "PHONE": "(313) 471-6000",
        "DAYS": "Sun - Thu, Fri - Sat",
        "HOURS": "10:30 AM - 10 PM, 10:30 AM - 11 PM",
        "OPTIONS": "Delivery, Takeout",
        "DISCOUNTS": "None",
        "NOTES": "*714-528-8374. Doordash",
        "DEL_OPTS": "Doordash, Postmates",
        "TYPE": "Pizza",
        "WEBSITE": "https://littlecaesars.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": "https://postmates.com/merchant/little-caesars-pizza-placentia-1",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13122017.86691879,
            "y": 4011745.6512722974,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 49,
        "NAME": "CITY BAGEL COMPANY",
        "ADDR": "1225 E YORBA LINDA BLVD",
        "PHONE": "(714) 572-0220",
        "DAYS": "Mon - Fri | Sat | Sun",
        "HOURS": "6 AM - 3 PM, 6:30 AM - 2PM, 6:30 AM - 1 PM",
        "OPTIONS": "Delivery, Takeout",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": "Grubhub, Doordash, Seamless",
        "TYPE": "Bagels",
        "WEBSITE": "https://www.citybagel.co/",
        "Doordash": "https://www.doordash.com/store/our-city-bagelry-placentia-765250/en-US",
        "Grubhub": "https://www.grubhub.com/restaurant/our-city-bagelry-1225-e-yorba-linda-blvd-placentia/555954",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13117973.688520731,
            "y": 4013920.6422460056,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 50,
        "NAME": "EL CANTARITO RESTAURANT",
        "ADDR": "120 W SANTA FE AVE",
        "PHONE": "(714) 528-6090",
        "DAYS": "Mon - Sun",
        "HOURS": "8 AM - 8 PM, May change to 10 AM - 7/8 PM",
        "OPTIONS": "Takeout",
        "DISCOUNTS": " ",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "TYPE": "Mexican",
        "WEBSITE": "https://elcantaritocuisine.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121440.87774747,
            "y": 4011210.7924953713,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 51,
        "NAME": "ESTHER'S TACO HOUSE",
        "ADDR": "2001 E ORANGETHORPE AVE",
        "PHONE": "(714) 996-2397",
        "DAYS": "Mon - Sun",
        "HOURS": "11 AM - 8:30 PM",
        "OPTIONS": "Takeout, Delivery",
        "DISCOUNTS": " ",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "TYPE": "Mexican",
        "WEBSITE": "https://estherstacos.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13115675.288879009,
            "y": 4011019.5865359493,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 52,
        "NAME": "INTERNATIONAL HOUSE OF PANCAKES",
        "ADDR": "131 N KRAEMER BLVD",
        "PHONE": "(714) 528-7838",
        "DAYS": "Mon - Sun",
        "HOURS": "8 AM - 4 PM",
        "OPTIONS": "Delivery, Takeout",
        "DISCOUNTS": " ",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "TYPE": "American",
        "WEBSITE": "https://ihop.com",
        "Doordash": " ",
        "Grubhub": "https://www.grubhub.com/restaurant/ihop-131-n-kramer-blvd-placentia/945585",
        "Postmates": "https://postmates.com/merchant/ihop-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120458.602214657,
            "y": 4011560.4706277694,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 53,
        "NAME": "JACK-IN-BOX #3548",
        "ADDR": "2097 E ORANGETHORPE AVE",
        "PHONE": "(949) 606-4256",
        "DAYS": "Mon - Sun",
        "HOURS": "6 AM - Midnight",
        "OPTIONS": "Doordash ONLY//Drive-Thru",
        "DISCOUNTS": " ",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "TYPE": "Burgers, Fast Food",
        "WEBSITE": "https://jackinthebox.com",
        "Doordash": "https://www.doordash.com/store/jack-in-the-box-placentia-393440/en-US",
        "Grubhub": "https://www.grubhub.com/restaurant/jack-in-the-box-2097-e-orangethorpe-ave-placentia/649108",
        "Postmates": "https://postmates.com/merchant/jack-in-the-box-placentia-2",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13115602.75328731,
            "y": 4010998.748292223,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 54,
        "NAME": "JERSEY MIKE'S SUBS",
        "ADDR": "850 N ROSE DR",
        "PHONE": "(714) 996-5553",
        "DAYS": "Mon - Sun",
        "HOURS": "10 AM - 8 PM",
        "OPTIONS": "Online, Takeout, Phone, 3rd Party Delivery",
        "DISCOUNTS": " ",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "TYPE": "Sandwich",
        "WEBSITE": "https://jerseymikes.com",
        "Doordash": " ",
        "Grubhub": "https://www.grubhub.com/restaurant/jersey-mikes-850-n-rose-dr-ste-c-placentia/1132389",
        "Postmates": "https://postmates.com/merchant/jersey-mikes-subs-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118162.461616402,
            "y": 4012523.0131672714,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 55,
        "NAME": "STARBUCKS COFFEE #541",
        "ADDR": "1474 N KRAEMER BLVD",
        "PHONE": "(206) 318-8705",
        "DAYS": "Mon - Sun",
        "HOURS": "5 AM - 8 PM",
        "OPTIONS": "Takeout, Drive-Thru, 3rd party Delivery",
        "DISCOUNTS": "None",
        "NOTES": "*Ubereats only. 714-577-8620",
        "DEL_OPTS": "Ubereats",
        "TYPE": "Coffee",
        "WEBSITE": "https://starbucks.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120437.835755944,
            "y": 4013714.0116992784,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 56,
        "NAME": "THE FLAME BROILER",
        "ADDR": "2001 E ORANGETHORPE AVE",
        "PHONE": "(714) 579-7585",
        "DAYS": "Mon - Sun",
        "HOURS": "10 AM - 8 PM",
        "OPTIONS": "Takeout",
        "DISCOUNTS": " ",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "TYPE": "Asian Fusion",
        "WEBSITE": "https://flamebroilerusa.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13115675.240083368,
            "y": 4010980.2592250346,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 57,
        "NAME": "THE PIZZA STORE",
        "ADDR": "2091 E ORANGETHORPE AVE",
        "PHONE": "(714) 528-4700",
        "DAYS": "Mon - Sat, Sun",
        "HOURS": "10 AM - 9 PM, 11 AM - 9 PM",
        "OPTIONS": "Takeout, Delivery",
        "DISCOUNTS": " ",
        "NOTES": "*Grubhub, Ubereats, Slice",
        "DEL_OPTS": "Grubhub, Ubereats, Slice",
        "TYPE": "Pizza",
        "WEBSITE": "https://thepizza.store",
        "Doordash": " ",
        "Grubhub": "https://www.grubhub.com/restaurant/the-pizza-store--more-2091-e-orangethorpe-ave-placentia/258776",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13115599.786770478,
            "y": 4011084.826968894,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 58,
        "NAME": "TONY'S LITTLE ITALY PIZZA",
        "ADDR": "1808 N PLACENTIA AVE",
        "PHONE": "(714) 528-2159",
        "DAYS": "Mon - Sun",
        "HOURS": "11 AM - 10 PM",
        "OPTIONS": "Takeout, Delivery",
        "DISCOUNTS": " ",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "TYPE": "Pizza",
        "WEBSITE": "https://tonyslittleitaly.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121461.750047142,
            "y": 4014793.614285435,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 59,
        "NAME": "SAN SUSHI",
        "ADDR": "161 W SANTA FE AVE",
        "PHONE": "(714) 203-1123",
        "DAYS": "Sun - Thurs, Fri - Sat",
        "HOURS": "11 AM - 8:30 PM, 11 AM - 9:30 PM",
        "OPTIONS": "Takeout, Delivery",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": "Grubhub, Doordash, Postmates",
        "TYPE": "Sushi",
        "WEBSITE": "https://3sansushi.com/",
        "Doordash": "https://www.doordash.com/store/san-sushi-placentia-456560/en-US",
        "Grubhub": "https://www.grubhub.com/restaurant/san-sushi-161-w-santa-fe-ave-placentia/1050393",
        "Postmates": "https://postmates.com/merchant/san-sushi-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121455.843699178,
            "y": 4011254.153139051,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 60,
        "NAME": "TEAHOLIC",
        "ADDR": "660 S PLACENTIA AVE",
        "PHONE": "(657) 216-0685",
        "DAYS": "Mon- Fri, Sat",
        "HOURS": "10:30 AM- 7:30PM, 11AM-5PM",
        "OPTIONS": "Takeout, Delivery, 3rd party Delivery",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": "Doordash, Grubhub, Seamless, Postmates",
        "TYPE": "Asian Fusion",
        "WEBSITE": "https://teaholic-asian-fusion-restaurant.business.site/",
        "Doordash": "https://www.doordash.com/store/teaholic-cafe-placentia-690775/en-US",
        "Grubhub": "https://www.grubhub.com/restaurant/teaholic-cafe-660-s-placentia-ave-placentia/1309315",
        "Postmates": "https://postmates.com/merchant/teaholic-cafe-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13122468.550966447,
            "y": 4010482.8659160933,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 61,
        "NAME": "DEL TACO",
        "ADDR": "1851 E ORANGETHORPE AVE",
        "PHONE": "(714) 996-4089",
        "DAYS": "Mon - Sun",
        "HOURS": "24 HR",
        "OPTIONS": "Curbside, 3rd party Delivery",
        "DISCOUNTS": " ",
        "NOTES": " ",
        "DEL_OPTS": "Ubereats, Doordash, Grubhub, Postmates",
        "TYPE": "Mexican",
        "WEBSITE": "https://deltaco.com",
        "Doordash": "https://www.doordash.com/store/del-taco-placentia-548381/en-US",
        "Grubhub": "https://www.grubhub.com/restaurant/del-taco-1851-e-orangethorpe-ave-placentia/1037474",
        "Postmates": "https://postmates.com/merchant/del-taco-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13116241.006170055,
            "y": 4011078.3345258893,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 62,
        "NAME": 'TORTAS & BIONICOS "NICE"',
        "ADDR": "616 W CHAPMAN AVE",
        "PHONE": "(657) 444-9100",
        "DAYS": "Mon - Sun",
        "HOURS": "9 AM - 8 PM",
        "OPTIONS": "Takeout only, 3rd party Delivery",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": "Postmates, Grubhub, Doordash, Ubereats",
        "TYPE": "Mexican",
        "WEBSITE": " ",
        "Doordash": "https://www.doordash.com/store/tortas-bionicos-nice-placentia-682314/en-US",
        "Grubhub": "https://www.grubhub.com/restaurant/tortas-y-bionicos-nice-616-w-chapman-ave-placentia/1431030",
        "Postmates": "https://postmates.com/merchant/tortas-bionicos-nice-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121963.847252158,
            "y": 4011731.161359353,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 63,
        "NAME": "GOLDEN STATE COFFEE ROASTERS",
        "ADDR": "109 W SANTA FE AVE",
        "PHONE": "(714)646-9652",
        "DAYS": "Mon - Fri, Sat-Sun",
        "HOURS": " 7AM- 2PM, 7AM-4PM",
        "OPTIONS": "Takeout",
        "DISCOUNTS": " ",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "TYPE": "Coffee",
        "WEBSITE": "https://www.goldenstate.coffee/",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121417.017810738,
            "y": 4011245.7070777365,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 64,
        "NAME": "PHO NOODLE HOUSE",
        "ADDR": "646 N ROSE DR",
        "PHONE": "(714)572 3907",
        "DAYS": "Mon - Sun",
        "HOURS": "10 AM - 8 PM",
        "OPTIONS": "Takeout, Delivery, 3rd party Delivery",
        "DISCOUNTS": " ",
        "NOTES": " ",
        "DEL_OPTS": "Doordash, Grubhub, Ubereat, Postmate",
        "TYPE": "Vietnamese",
        "WEBSITE": "https://www.phonoodlehousetogo.com/",
        "Doordash": "https://www.doordash.com/store/pho-noodle-house-placentia-135469/en-US",
        "Grubhub": "https://www.grubhub.com/restaurant/pho-noodle-house-646-n-rose-dr-placentia/477407",
        "Postmates": "https://postmates.com/merchant/pho-noodle-house-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118104.073689418,
            "y": 4012287.1369453175,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 65,
        "NAME": "CLUBHOUSE GRILLE AND SPIRITS",
        "ADDR": "2053 E ORANGETHORPE AVE",
        "PHONE": "(714) 528-7000",
        "DAYS": "Mon - Sun",
        "HOURS": "9 AM - 8 PM",
        "OPTIONS": "Takeout",
        "DISCOUNTS": " ",
        "NOTES": " ",
        "DEL_OPTS": "Toasttab",
        "TYPE": "Bar & Grill",
        "WEBSITE": "http://clubhouse-grille.cafes-usa.com/",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": "https://www.toasttab.com/clubhousegrille/v3",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13115655.070707675,
            "y": 4011088.050120493,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 66,
        "NAME": "THE BRUERY",
        "ADDR": "717 DUNN WAY",
        "PHONE": "(714)996-6258",
        "DAYS": "Mon - Sun",
        "HOURS": "12PM - 8PM",
        "OPTIONS": "Delivery",
        "DISCOUNTS": " ",
        "NOTES": "Mon-Sun, order before 2p for same-day delivery",
        "DEL_OPTS": "The Bruery",
        "TYPE": "Brewery",
        "WEBSITE": "https://www.thebruery.com/",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13122254.122879904,
            "y": 4010335.7401455487,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 67,
        "NAME": "BASKIN ROBBINS",
        "ADDR": "104 E YORBA LINDA BLVD",
        "PHONE": "(714) 528-3443",
        "DAYS": "Mon - Sun",
        "HOURS": "11AM -10PM",
        "OPTIONS": " ",
        "DISCOUNTS": " ",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "TYPE": "Ice Cream",
        "WEBSITE": " ",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120763.302871045,
            "y": 4013677.9404833005,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 68,
        "NAME": "RICH FARM ICE CREAM",
        "ADDR": "901 E YORBA LINDA BLVD",
        "PHONE": "(714) 854-7424",
        "DAYS": "Sun - Thur, Fri - Sun",
        "HOURS": "1PM - 8PM, 1PM - 9PM",
        "OPTIONS": "Takeout",
        "DISCOUNTS": " ",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "TYPE": "Ice Cream",
        "WEBSITE": "www.richfarmicecream.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118760.728346163,
            "y": 4014017.4764727745,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 69,
        "NAME": "SUBWAY",
        "ADDR": "1085 E IMPERIAL HWY",
        "PHONE": "(714)572-6488",
        "DAYS": "Mon - Fri, Sat - Sun",
        "HOURS": "10 AM - 6:30 PM, 11 AM - 6 PM",
        "OPTIONS": "Takeout, 3rd party Delivery",
        "DISCOUNTS": " ",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "TYPE": "Sandwich",
        "WEBSITE": "https://subway.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118448.340282472,
            "y": 4016172.1516459133,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 70,
        "NAME": "MR. D'S",
        "ADDR": "126 E. YORBA LINDA BLVD",
        "PHONE": "(714) 985-1111",
        "DAYS": "Mon-Thurs, Fri-Sat, Sun",
        "HOURS": "6AM-9PM, 6AM-9:30PM, 7AM-9PM",
        "OPTIONS": "Takeout",
        "DISCOUNTS": " ",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "TYPE": "American",
        "WEBSITE": "https://www.mrdsrestaurants.com/",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120680.787720827,
            "y": 4013691.077077371,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 71,
        "NAME": "TLAQUEPAQUE",
        "ADDR": "101 W. SANTA FE AVE",
        "PHONE": "(714) 528-0110",
        "DAYS": "Tues-Sat, Sun",
        "HOURS": "11AM-3PM/5-9PM, 10AM-8:30PM",
        "OPTIONS": "Takeout",
        "DISCOUNTS": " ",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "TYPE": "Mexican",
        "WEBSITE": "https://tlaquepaquerestaurant.com/",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121396.379836056,
            "y": 4011239.108769269,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 72,
        "NAME": "THE ORIGINAL PANCAKE HOUSE",
        "ADDR": "1454 N. KRAEMER BLVD",
        "PHONE": "(714) 983-7771",
        "DAYS": "Mon-Sun",
        "HOURS": "6AM-1PM",
        "OPTIONS": "Takeout, Delivery",
        "DISCOUNTS": " ",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "TYPE": "Breakfast & Brunch",
        "WEBSITE": "https://www.originalpancakehouse.com/",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120323.36865964,
            "y": 4013673.2998090424,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 73,
        "NAME": "EL FAROLITO",
        "ADDR": "201 S. BRADFORD AVE",
        "PHONE": "(714) 993-7880",
        "DAYS": "Mon-Sun",
        "HOURS": "7AM-8PM",
        "OPTIONS": "Takeout",
        "DISCOUNTS": " ",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "TYPE": "Mexican",
        "WEBSITE": "http://www.elfarolitomex.com/",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121354.337559497,
            "y": 4011422.2045109645,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 74,
        "NAME": "REMBRANDTS KITCHEN AND BAR",
        "ADDR": "909 E YORBA LINDA BLVD",
        "PHONE": "(714)203-1353",
        "DAYS": "Thurs-Sun",
        "HOURS": "5:00PM-10:00PM",
        "OPTIONS": "Takeout",
        "DISCOUNTS": " ",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "TYPE": "Italian",
        "WEBSITE": "https://www.rkboc.com/",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118684.669752972,
            "y": 4013997.8741680197,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
]

# download shapefile and upload to respective portal if not already present
polygon_data = "https://earthworks.stanford.edu/catalog/stanford-dc841dq9031"

test_items = [
    "1ac6896bcafc4dccb29c70f45c442b00",  # Polygon Zips
    "5fdb2869753140c8836353097b207591",  # US Hospitals
    "2150d4ebe2124f4c821f43de49a6c679",  # US Airports
]
profiles = ["online_test", "ent_test", "kube_test"]
setup_profiles(
    profiles[0],
    profiles[1],
    profiles[2],
)
stage_data(test_items)


@integration_test
class TestJoinFeatures(unittest.TestCase):
    def test_overwrite_layer(self):
        """tests overwriting an Item layer using the context param"""
        for profile in profiles:
            # establish gis connection
            gis = GIS(profile=profile, verify_cert=False)
            print("User: ", gis.users.me.username)
            # add point layer to portal
            sdf = pd.DataFrame(data)
            fs = gis.content.import_data(sdf)
            # gather layers
            point_item = gis.content.get(fs.id)
            if gis._is_agol:
                polygon_item = gis.content.get("1ac6896bcafc4dccb29c70f45c442b00")
            else:
                polygon_item = gis.content.get("1ac6896bcafc4dccb29c70f45c442b00")
            assert isinstance(point_item, Item)
            assert isinstance(polygon_item, Item)
            point_layer = point_item.layers[0]
            polygon_layer = polygon_item.layers[0]
            assert isinstance(point_layer, FeatureLayer)
            assert isinstance(polygon_layer, FeatureLayer)

            # create layer that will be overwritten
            test_id = str(datetime.datetime.now().microsecond)
            output_name = "test_join_features_" + test_id
            target_item = join_features(
                target_layer=polygon_layer,
                join_layer=point_layer,
                spatial_relationship="withindistance",
                spatial_relationship_distance=10,
                spatial_relationship_distance_units="Meters",
                output_name=output_name,
            )
            assert isinstance(target_item, Item)
            target_layer = target_item.layers[0]
            new_polygon_layer = polygon_item.layers[0]
            assert isinstance(target_layer, FeatureLayer)
            assert isinstance(new_polygon_layer, FeatureLayer)

            # perform overwrite
            overwrite = join_features(
                target_layer=polygon_layer,
                join_layer=point_layer,
                spatial_relationship="withindistance",
                spatial_relationship_distance=8,
                spatial_relationship_distance_units="Meters",
                output_name=target_layer,
                context={
                    "overwrite": True,
                },
            )
            assert isinstance(overwrite, Item)
            assert target_item.id == overwrite.id
            # overwrite should not append. Only one layer should be present
            assert len(target_item.layers) == 1

            # delete items that were added for test purpose
            assert target_item.delete()
            assert fs.delete()

    def test_overwrite_table(self):
        """tests overwriting an Item table using the context param"""
        for profile in profiles:
            # establish gis connection
            gis = GIS(profile=profile, verify_cert=False)
            print("User: ", gis.users.me.username)
            if gis._is_agol:
                us_hospitals = gis.content.get("5fdb2869753140c8836353097b207591")
                us_airports = gis.content.get("2150d4ebe2124f4c821f43de49a6c679")
            else:
                us_hospitals = gis.content.get("5fdb2869753140c8836353097b207591")
                us_airports = gis.content.get("2150d4ebe2124f4c821f43de49a6c679")
            assert isinstance(us_hospitals, Item)
            assert isinstance(us_airports, Item)
            airport_table = us_airports.tables[0]
            hospital_table = us_hospitals.tables[0]
            assert isinstance(airport_table, FeatureLayer)
            assert isinstance(hospital_table, FeatureLayer)

            # create layer that will be overwritten
            test_id = str(datetime.datetime.now().microsecond)
            output_name = "test_join_features_" + test_id
            target_item = join_features(
                target_layer=airport_table,
                join_layer=hospital_table,
                attribute_relationship=[
                    {"targetField": "CITY", "operator": "equal", "joinField": "CITY"}
                ],
                output_name=output_name,
            )
            assert isinstance(target_item, Item)
            target_table = target_item.tables[0]
            assert isinstance(target_table, Table)

            # perform overwrite
            overwrite = join_features(
                target_layer=airport_table,
                join_layer=hospital_table,
                attribute_relationship=[
                    {"targetField": "STATE", "operator": "equal", "joinField": "STATE"}
                ],
                output_name=target_table,
                context={
                    "overwrite": True,
                },
            )
            assert isinstance(overwrite, Item)
            assert target_item.id == overwrite.id
            # overwrite should not append. Only one layer should be present
            assert len(target_item.tables) == 1

            # delete items that were added for test purpose
            assert target_item.delete()


if __name__ == "__main__":
    unittest.main()
