import datetime
import unittest
import pandas as pd
from arcgis.gis import GIS, Item
from arcgis.features import FeatureLayer
from arcgis.features.analyze_patterns import interpolate_points
from .config_tests import setup_profiles
from utils.decorators import integration_test


data = [
    {
        "FID": 1,
        "NAME": "MARKET FRESH GRILL CAFE",
        "ADDR": "221 W ORANGETHORPE AVE",
        "PHONE": "(714) 528-1977",
        "DAYS": "Mon - Sun",
        "HOURS": "7 AM - 9 PM",
        "OPTIONS": "Takeout, Delivery, Drive-Thru",
        "DISCOUNTS": "(School, Fire/Police, Senior Discounts)",
        "NOTES": "*Grubhub, Postmates, Doordash",
        "DEL_OPTS": "Grubhub, Postmates, Doordash",
        "Workers": 7,
        "TYPE": "American",
        "WEBSITE": "https://marketfreshgrillcafe.com",
        "Doordash": " ",
        "Grubhub": "https://www.grubhub.com/restaurant/market-fresh-grill-cafe-221-w-orangethorpe-ave-placentia/1290830",
        "Postmates": "https://postmates.com/merchant/toms-place-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121824.265019992,
            "y": 4010311.1421616497,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 2,
        "NAME": "301 CAFE",
        "ADDR": "301 W SANTA FE AVE",
        "PHONE": "(714) 996-8001",
        "DAYS": "Mon - Sat",
        "HOURS": "10 AM - 9:30 PM",
        "OPTIONS": "Takeout, 3rd party Delivery",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": "Doordash",
        "Workers": 7,
        "TYPE": "Mexican",
        "WEBSITE": " ",
        "Doordash": "https://www.doordash.com/store/301-cafe-placentia-723324/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121629.643094601,
            "y": 4011297.297220264,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 3,
        "NAME": "Q TORTAS",
        "ADDR": "220 S BRADFORD AVE",
        "PHONE": "(714) 993-3270",
        "DAYS": "Tue - Friday, Sat - Sun",
        "HOURS": "11 AM - 8 PM, 9 AM - 8 PM",
        "OPTIONS": "Takeout",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "Workers": 17,
        "TYPE": "Mexican",
        "WEBSITE": " ",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121342.054302571,
            "y": 4011316.8427645396,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 4,
        "NAME": "THE WHOLE ENCHILADA",
        "ADDR": "106 E YORBA LINDA BLVD",
        "PHONE": "(714) 961-9123",
        "DAYS": "Mon - Sun",
        "HOURS": "11 AM - 8 PM",
        "OPTIONS": "Takeout, Delivery",
        "DISCOUNTS": "None",
        "NOTES": "*Doordash",
        "DEL_OPTS": "Doordash",
        "Workers": 2,
        "TYPE": "Mexican",
        "WEBSITE": "https://wholeenchilada.com",
        "Doordash": "https://www.doordash.com/store/the-whole-enchilada-placentia-56007/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120774.654751526,
            "y": 4013636.1349284584,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 5,
        "NAME": "AVALON BAGLES AND BURGERS",
        "ADDR": "174 E YORBA LINDA BLVD",
        "PHONE": "(714) 985-1382",
        "DAYS": "Mon - Sun",
        "HOURS": "7AM - 4 PM",
        "OPTIONS": "Takeout, 3rd party Delivery",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": "Grubhub, Doordash, Seamless",
        "Workers": 4,
        "TYPE": "Bagels, Burgers, Sandwiches",
        "WEBSITE": "https://avalonbagelstoburgers.com/",
        "Doordash": "https://www.doordash.com/store/avalon-bagels-to-burgers-placentia-320809/en-US",
        "Grubhub": "https://www.grubhub.com/restaurant/avalon-bagels-to-burgers---placentia-174-e-yorba-linda-blvd-placentia/553124",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120516.589507373,
            "y": 4013511.6346839233,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 6,
        "NAME": "ISE JAPANESE RESTAURANT",
        "ADDR": "1241 E YORBA LINDA BLVD",
        "PHONE": "(714) 993-6442",
        "DAYS": "Mon - Thur, Fri, Sat",
        "HOURS": "11 AM - 10 PM, 11 AM - 10:30 PM, 11:30 AM - 10 PM",
        "OPTIONS": "Takeout",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "Workers": 6,
        "TYPE": "Japanese",
        "WEBSITE": "https://isesushi.wordpress.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13117975.00648396,
            "y": 4013952.0928615234,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 7,
        "NAME": "COFFEE BEAN & TEA LEAF #392",
        "ADDR": "1188 E YORBA LINDA BLVD",
        "PHONE": "(310) 237-2326",
        "DAYS": "Mon - Sun",
        "HOURS": "6 AM - 6 PM",
        "OPTIONS": "Drive-Thru",
        "DISCOUNTS": "None",
        "NOTES": "657-216-5920",
        "DEL_OPTS": "Postmates",
        "Workers": 8,
        "TYPE": "Coffee",
        "WEBSITE": "https://coffeebean.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": "https://postmates.com/merchant/the-coffee-bean-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118132.860060971,
            "y": 4013795.8679011846,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 8,
        "NAME": "PORKY'S PIZZA",
        "ADDR": "1152 E IMPERIAL HWY",
        "PHONE": "(714) 572-1777",
        "DAYS": "Sun - Thur, Fri - Sat",
        "HOURS": "11 AM - 9 PM, 11 AM - 10 PM",
        "OPTIONS": "Takeout, Delivery",
        "DISCOUNTS": "None",
        "NOTES": "*Ubereats, Postmates, Doordash",
        "DEL_OPTS": "Ubereats, Postmates, Doordash",
        "Workers": 10,
        "TYPE": "Pizza",
        "WEBSITE": "https://porkyspizza.com",
        "Doordash": "https://www.doordash.com/store/porky-s-pizza-placentia-16731/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118260.5041459,
            "y": 4015977.511310816,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 9,
        "NAME": "FISH IN A BOTTLE",
        "ADDR": "1205 E IMPERIAL HWY",
        "PHONE": "(714) 528-4000",
        "DAYS": "Until this Sunday",
        "HOURS": "11:30 AM - 9:30 PM, Sat 11:30 AM -10:30, Sun 4 PM*",
        "OPTIONS": "Take-out",
        "DISCOUNTS": "None",
        "NOTES": "*Doordash, Postmates, call in orders only, Will n*",
        "DEL_OPTS": "Doordash, Postmates",
        "Workers": 12,
        "TYPE": "Sushi",
        "WEBSITE": "http://fish-in-a-bottle-sushi-grill.cafes-usa.com/",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": "https://postmates.com/merchant/fish-in-a-bottle-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118048.480420934,
            "y": 4015961.906490283,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 10,
        "NAME": "WINGSTOP #1553",
        "ADDR": "1093 E IMPERIAL HWY",
        "PHONE": "(714) 868-7000",
        "DAYS": "Mon - Sun",
        "HOURS": "10:30 AM - Midnight",
        "OPTIONS": "Delivery, Takeout",
        "DISCOUNTS": "Mondays & Tuesdays 60 cent boneless wings.",
        "NOTES": "*Doordash",
        "DEL_OPTS": "Doordash",
        "Workers": 14,
        "TYPE": "Chicken Wings",
        "WEBSITE": "https://wingstop.com",
        "Doordash": "https://www.doordash.com/store/wingstop-placentia-647491/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118439.698197426,
            "y": 4016169.0124437176,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 11,
        "NAME": "WIENERSCHNITZEL #626",
        "ADDR": "1005 E IMPERIAL HWY",
        "PHONE": "(714) 996-0570",
        "DAYS": "Mon - Sun",
        "HOURS": "10AM - 10PM",
        "OPTIONS": "Drive-Thru, 3rd party Delivery",
        "DISCOUNTS": "None",
        "NOTES": "*Ubereats. 714-996-0570",
        "DEL_OPTS": "Ubereats",
        "Workers": 1,
        "TYPE": "Hot dogs",
        "WEBSITE": "https://wienerschnitzel.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": "https://postmates.com/merchant/weinerschnitzel-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118485.377682252,
            "y": 4016191.4002631214,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 12,
        "NAME": "SUBWAY # 3443",
        "ADDR": "1807 E ORANGETHORPE AVE",
        "PHONE": "(714) 579-3160",
        "DAYS": "Mon - Fri",
        "HOURS": "8 AM - 4PM",
        "OPTIONS": "Takeout, 3rd party Delivery",
        "DISCOUNTS": "Website only",
        "NOTES": "*Postmates, Doordash",
        "DEL_OPTS": "Postmates, Doordash",
        "Workers": 3,
        "TYPE": "Sandwich",
        "WEBSITE": "https://subway.com",
        "Doordash": "https://www.doordash.com/store/subway-orange-county-placentia-57327/en-US",
        "Grubhub": " ",
        "Postmates": "https://postmates.com/merchant/subway-placentia-5",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13116301.460162882,
            "y": 4011152.5278131273,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 13,
        "NAME": "SAKE SUSHI & GRILL/JOO INC",
        "ADDR": "850 N ROSE DR",
        "PHONE": "(714) 528-7253",
        "DAYS": "Mon - Sun",
        "HOURS": "11:30 AM - 2:30 PM/5 PM - 9:30 PM (Sunday's 5 - 9*",
        "OPTIONS": "Takeout, Delivery",
        "DISCOUNTS": "Free Delivery Dinner only",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "Workers": 5,
        "TYPE": "Sushi",
        "WEBSITE": "https://sake-sushi-grill.cafes-usa.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": "https://postmates.com/merchant/sake-sushi-grill-placentia-59451",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118198.942123447,
            "y": 4012522.1051237006,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 14,
        "NAME": "KFC",
        "ADDR": "1404 N KRAEMER BLVD",
        "PHONE": "(562) 500-5940",
        "DAYS": "Mon - Sun",
        "HOURS": "10 AM - 10 PM varies",
        "OPTIONS": "Takeout",
        "DISCOUNTS": "None",
        "NOTES": "*Free Delivery thru KFC.com",
        "DEL_OPTS": " ",
        "Workers": 7,
        "TYPE": "Chicken",
        "WEBSITE": "https://kfc.com",
        "Doordash": " ",
        "Grubhub": "https://www.grubhub.com/restaurant/kfc-1404-n-kraemer-blvd-placentia/936214",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120433.63573153,
            "y": 4013632.9932656037,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 15,
        "NAME": "MCDONALD'S",
        "ADDR": "770 W CHAPMAN AVE",
        "PHONE": "(714) 630-9430",
        "DAYS": "Mon - Sun",
        "HOURS": "6 AM - 2 AM",
        "OPTIONS": "Drive-Thru",
        "DISCOUNTS": "None",
        "NOTES": "*714-577-8171. Ubereats, Doordash",
        "DEL_OPTS": "Ubereats, Doordash",
        "Workers": 9,
        "TYPE": "Burgers, Fast Food",
        "WEBSITE": "https://mcdonalds.com",
        "Doordash": "https://www.doordash.com/store/mcdonald-s-placentia-653621/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13122186.242973486,
            "y": 4011840.121557618,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 16,
        "NAME": "WABA GRILL #204",
        "ADDR": "720 N ROSE DR",
        "PHONE": "(714) 577-9222",
        "DAYS": "Mon - Sat, Sun",
        "HOURS": "11AM - 8 PM, 11 AM - 8 PM",
        "OPTIONS": "Takeout, Delivery",
        "DISCOUNTS": "4 Chicken Bowls for $20, Family Meal $19.99",
        "NOTES": "*Postmates, Grubhub, Doordash, Ubereats",
        "DEL_OPTS": "Postmates, Grubhub, Doordash, Ubereats",
        "Workers": 7,
        "TYPE": "Asian Fusion",
        "WEBSITE": "https://wabagrill.com",
        "Doordash": "https://www.doordash.com/store/waba-grill-placentia-187728/en-US",
        "Grubhub": "https://www.grubhub.com/restaurant/waba-grill-720-n-rose-dr-placentia/625459",
        "Postmates": "https://postmates.com/merchant/waba-grill-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118102.344055684,
            "y": 4012420.7617618423,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 17,
        "NAME": "MINI GOURMET",
        "ADDR": "1210 E YORBA LINDA BLVD",
        "PHONE": "(714) 524-1611",
        "DAYS": "Thur-Tue",
        "HOURS": "6:30 AM - 2 PM",
        "OPTIONS": "Takeout",
        "DISCOUNTS": "5% Discounts off total purchase",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "Workers": 13,
        "TYPE": "Breakfast & Brunch",
        "WEBSITE": "https://mini-gourmet-restaurant.business.site",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118016.23447817,
            "y": 4013710.0375595465,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 18,
        "NAME": "MCDONALD'S OF PLACENTIA",
        "ADDR": "164 E YORBA LINDA BLVD",
        "PHONE": "(714) 993-3121",
        "DAYS": "Mon - Sun",
        "HOURS": "5 AM - Midnight",
        "OPTIONS": "Delivery, Drive-up",
        "DISCOUNTS": "None",
        "NOTES": "*Doordash, Ubereats",
        "DEL_OPTS": "Doordash, Ubereats",
        "Workers": 9,
        "TYPE": "Burgers, Fast Food",
        "WEBSITE": "https://mcdonalds.com",
        "Doordash": "https://www.doordash.com/store/mcdonald-s-placentia-662251/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120507.813723624,
            "y": 4013598.500116996,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 19,
        "NAME": "TACO BELL",
        "ADDR": "1174 E YORBA LINDA BLVD",
        "PHONE": "(714) 528-3122",
        "DAYS": "Mon - Sun",
        "HOURS": "10 AM - 11 PM",
        "OPTIONS": "Drive-Thru, 3rd party Delivery",
        "DISCOUNTS": "None",
        "NOTES": "714-528-3122. Grubhub, Postmates, Ubereats, Doord*",
        "DEL_OPTS": "Grubhub, Postmates, Ubereats, Doordash",
        "Workers": 15,
        "TYPE": "Mexican",
        "WEBSITE": "https://locations.tacobell.com/ca/placentia/1174-yorba-linda-blvd-.html",
        "Doordash": " ",
        "Grubhub": "https://www.grubhub.com/restaurant/taco-bell-1174-e-yorba-linda-blvd-placentia/927181",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118168.328904405,
            "y": 4013789.6247696993,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 20,
        "NAME": "DUKE'S CAFE",
        "ADDR": "2099 E ORANGETHORPE AVE",
        "PHONE": "(714) 983-7056",
        "DAYS": "Mon- Sun",
        "HOURS": "7 AM - 9 PM",
        "OPTIONS": "Takeout, 3rd party Delivery",
        "DISCOUNTS": "None",
        "NOTES": "*Doordash, ChowNow",
        "DEL_OPTS": "Doordash, ChowNow",
        "Workers": 21,
        "TYPE": "Breakfast & Brunch, Mexican, Sandwiches",
        "WEBSITE": "https://dukescafeyl.com",
        "Doordash": "https://www.doordash.com/store/duke-s-cafe-placentia-55927/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13115541.226824583,
            "y": 4010967.5127567225,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 21,
        "NAME": "PIZZA HUT DELIVERY # 24890",
        "ADDR": "901 E YORBA LINDA BLVD UNIT A",
        "PHONE": "(714) 996-4222",
        "DAYS": "Sun - Thur, Fri- Sat",
        "HOURS": "10 AM - Midnight, 10 AM - 1 AM",
        "OPTIONS": "Pickup, Delivery",
        "DISCOUNTS": "Specials only, available online",
        "NOTES": "*Grubhub, Doordash",
        "DEL_OPTS": "Grubhub, Doordash, Pizza Hut",
        "Workers": 9,
        "TYPE": "Pizza",
        "WEBSITE": "https://pizzahutdelivery.com",
        "Doordash": " ",
        "Grubhub": "https://www.grubhub.com/restaurant/pizza-hut-901-e-yorba-linda-blvd-placentia/1128198",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118794.10913479,
            "y": 4014016.9734648396,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 22,
        "NAME": "JACK IN THE BOX #3253",
        "ADDR": "1097 E IMPERIAL HWY",
        "PHONE": "(714) 528-2960",
        "DAYS": "Mon - Sun",
        "HOURS": "6 AM - Midnight",
        "OPTIONS": "Takeout, Drive-Thru",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "Workers": 9,
        "TYPE": "Burgers, Fast Food",
        "WEBSITE": "https://jackinthebox.com",
        "Doordash": " ",
        "Grubhub": "https://www.grubhub.com/restaurant/jack-in-the-box-1097-e-imperial-hwy-placentia/669594",
        "Postmates": "https://postmates.com/merchant/jack-in-the-box-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118406.05624054,
            "y": 4016152.8211497087,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 23,
        "NAME": "DEL TACO, LLC #917",
        "ADDR": "1171 E IMPERIAL HWY",
        "PHONE": "(714) 985-9095",
        "DAYS": "Mon - Sun",
        "HOURS": "24 HR",
        "OPTIONS": "Curbside, 3rd party Delivery",
        "DISCOUNTS": "None",
        "NOTES": "Ubereats, Doordash, Grubhub, Postmates",
        "DEL_OPTS": "Ubereats, Doordash, Grubhub, Postmates",
        "Workers": 9,
        "TYPE": "Mexican",
        "WEBSITE": "https://deltaco.com",
        "Doordash": "https://www.doordash.com/store/del-taco-placentia-548449/en-US",
        "Grubhub": "https://www.grubhub.com/restaurant/del-taco-1171-e-imperial-highway-placentia/1027911",
        "Postmates": "https://postmates.com/merchant/del-taco-placentia-1",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118171.300098535,
            "y": 4016033.4662593096,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 24,
        "NAME": "FANTASY BURGER",
        "ADDR": "510 W CHAPMAN AVE",
        "PHONE": "(714) 223-1981",
        "DAYS": "Mon - Sun",
        "HOURS": "6 AM - 10 PM, Sun 7 AM - 10 PM",
        "OPTIONS": "Take-Out, Drive Thru, 3rd Party Delivery",
        "DISCOUNTS": "None",
        "NOTES": "*None, Phone call or walk in orders for take-out",
        "DEL_OPTS": "None",
        "Workers": 18,
        "TYPE": "Burgers, Fast Food",
        "WEBSITE": "https://fantasy-burger.cafes-usa.com",
        "Doordash": "https://www.doordash.com/store/fantasy-burger-placentia-18612/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121824.990080802,
            "y": 4011730.078537878,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 25,
        "NAME": "LOS GALLOS RESTAURANT",
        "ADDR": "1667 E ORANGETHORPE AVE",
        "PHONE": "(714) 579-7955",
        "DAYS": "Mon - Sun",
        "HOURS": "11 AM - 6:30 PM",
        "OPTIONS": "Takeout",
        "DISCOUNTS": "None",
        "NOTES": "*Also has been receiving fradulent phone calls fr*",
        "DEL_OPTS": "Doordash",
        "Workers": 18,
        "TYPE": "Mexican",
        "WEBSITE": " ",
        "Doordash": "https://www.doordash.com/store/los-gallos-placentia-682330/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13116713.940300839,
            "y": 4011162.386565792,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 26,
        "NAME": "CARL'S JR #663",
        "ADDR": "750 N ROSE DR",
        "PHONE": "(805) 672-2889",
        "DAYS": "Mon - Sun",
        "HOURS": "6 AM - 11PM",
        "OPTIONS": "Delivery, Takeout, Drive-Thru",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": "Grubhub",
        "Workers": 18,
        "TYPE": "Burgers, Fast Food",
        "WEBSITE": "https://carlsjr.com",
        "Doordash": " ",
        "Grubhub": "https://www.grubhub.com/restaurant/carls-jr-1285-e-imperial-hwy-placentia/1016047",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118237.315790087,
            "y": 4012395.985027623,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 27,
        "NAME": "SUBWAY 29842",
        "ADDR": "1208 E YORBA LINDA BLVD",
        "PHONE": "(714) 579-6555",
        "DAYS": "Mon - Fri, Sat - Sun",
        "HOURS": "10 AM - 7PM, 11 AM - 6:30 PM",
        "OPTIONS": "Delivery, Takeout",
        "DISCOUNTS": "None",
        "NOTES": "*Ubereats, Grubhub, Postmates, Doordash",
        "DEL_OPTS": "Ubereats, Grubhub, Postmates, Doordash",
        "Workers": 10,
        "TYPE": "Sandwich",
        "WEBSITE": "https://subway.com",
        "Doordash": "https://www.doordash.com/store/subway-placentia-381793/en-US",
        "Grubhub": "https://www.grubhub.com/restaurant/subway-1208-e-yorba-linda-blvd-placentia/1065086",
        "Postmates": "https://postmates.com/merchant/subway-placentia-1",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118023.658378506,
            "y": 4013710.37327354,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 28,
        "NAME": "COCINA AZTECA GRILL LLC",
        "ADDR": "111 E CHAPMAN AVE",
        "PHONE": "(714) 577-9900",
        "DAYS": "Mon - Sun",
        "HOURS": "8 AM - 8 PM",
        "OPTIONS": "Delivery, Takeout",
        "DISCOUNTS": "None",
        "NOTES": "*Ubereats, Doordash, Postmates, Online Order (Coc*",
        "DEL_OPTS": "Ubereats, Doordash, Postmates",
        "Workers": 5,
        "TYPE": "Mexican",
        "WEBSITE": "https://cocinaaztecagrill.com",
        "Doordash": " ",
        "Grubhub": "https://www.grubhub.com/restaurant/cocina-azteca-e-chapman-ave-old-name-111-e-chapman-ave-placentia/1939612",
        "Postmates": "https://postmates.com/merchant/cocina-azteca-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121233.98441139,
            "y": 4011666.5631723735,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 29,
        "NAME": "MOO CAFE, LLC",
        "ADDR": "118 N BRADFORD AVE",
        "PHONE": "(714) 646-9311",
        "DAYS": "Sun - Thur, Fri - Sun",
        "HOURS": "11 AM - 8 PM, 11 AM - 9 PM",
        "OPTIONS": "Takeout, Delivery",
        "DISCOUNTS": "None",
        "NOTES": "*Grubhub, Ubereats",
        "DEL_OPTS": "Grubhub, Ubereats",
        "Workers": 1,
        "TYPE": "Tea House",
        "WEBSITE": "https://moocafeco.com",
        "Doordash": "https://www.doordash.com/store/moo-cafe-placentia-824819/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121194.842499591,
            "y": 4011760.301052922,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 30,
        "NAME": "PHILLY'S BEST",
        "ADDR": "198 E YORBA LINDA BLVD",
        "PHONE": "(714) 996-3278",
        "DAYS": "Mon - Sat, Sun",
        "HOURS": "10 AM - 9 AM, 11 AM - 8 PM",
        "OPTIONS": "Takeout",
        "DISCOUNTS": "None",
        "NOTES": "*Doordash, Postmates",
        "DEL_OPTS": "Doordash, Postmates",
        "Workers": 5,
        "TYPE": "Sandwich",
        "WEBSITE": "https://eatphillysbest.com/",
        "Doordash": "https://www.doordash.com/store/philly-s-best-placentia-16702/en-US",
        "Grubhub": " ",
        "Postmates": "https://postmates.com/merchant/phillys-best-placentia-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120479.211405389,
            "y": 4013465.3630684135,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 31,
        "NAME": "CRAFTSMAN WOOD FIRED PIZZA",
        "ADDR": "148 E YORBA LINDA BLVD",
        "PHONE": "(714) 579-1777",
        "DAYS": "Mon - Sun",
        "HOURS": "4 PM - 7 PM",
        "OPTIONS": "Curbside, Delivery",
        "DISCOUNTS": " ",
        "NOTES": "*Closed but will reopen March 23. Delivery throug*",
        "DEL_OPTS": "Postmates, Slice",
        "Workers": 5,
        "TYPE": "Pizza",
        "WEBSITE": "https://craftsmanpizza.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": "https://postmates.com/merchant/craftsman-wood-fired-pizza-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120610.333340239,
            "y": 4013534.0243102526,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 32,
        "NAME": "DOMINO'S PIZZA #8170",
        "ADDR": "1913 N PLACENTIA AVE",
        "PHONE": "(562) 522-6925",
        "DAYS": "Sun - Thu, Fri - Sat",
        "HOURS": "10 AM - Midnight, 10 AM - 1 AM",
        "OPTIONS": "Delivery, Takout",
        "DISCOUNTS": "Specials only, available online",
        "NOTES": " ",
        "DEL_OPTS": "Dominos",
        "Workers": 80,
        "TYPE": "Pizza",
        "WEBSITE": "https://domino'spizza.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121534.992394976,
            "y": 4014959.5990541936,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 33,
        "NAME": "GINA MARIA'S PIZZERIA",
        "ADDR": "1525 N PLACENTIA AVE",
        "PHONE": "(714) 996-7371",
        "DAYS": "Tues - Thurs, Fri - Sat, Sun",
        "HOURS": "11 AM - 9 PM, 11 AM - 10 PM, 11 AM - 9 PM",
        "OPTIONS": "Takeout",
        "DISCOUNTS": "$12 Off 1st Order",
        "NOTES": "*Grubhub, Doordash, Seamless",
        "DEL_OPTS": "Grubhub, Doordash, Seamless",
        "Workers": 5,
        "TYPE": "Pizza",
        "WEBSITE": "https://myginamarias.com",
        "Doordash": "https://www.doordash.com/store/gina-maria-s-pizzeria-placentia-756799/en-US",
        "Grubhub": "https://www.grubhub.com/restaurant/gina-marias-pizzeria-1525-n-placentia-ave-placentia/1445600",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121714.55736742,
            "y": 4014210.2237393702,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 34,
        "NAME": "LITTLE CAESAR'S",
        "ADDR": "1212 E YORBA LINDA BLVD",
        "PHONE": "(909) 579-1583",
        "DAYS": "Mon - Sun",
        "HOURS": "11 AM - 10 PM",
        "OPTIONS": "Delivery, Takeout",
        "DISCOUNTS": "None",
        "NOTES": "*714-996-9600. Doordash, Postmates",
        "DEL_OPTS": "Doordash, Postmates",
        "Workers": 25,
        "TYPE": "Pizza",
        "WEBSITE": "https://littlecaesars.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": "https://postmates.com/merchant/little-caesars-pizza-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118008.241812466,
            "y": 4013710.5583820003,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 35,
        "NAME": "PEPZ PIZZA IN PLACENTIA",
        "ADDR": "732 N ROSE DR",
        "PHONE": "(714) 572-2100",
        "DAYS": "Mon - Sun",
        "HOURS": "11 AM - 9 PM",
        "OPTIONS": "Pickup, Delivery",
        "DISCOUNTS": "None",
        "NOTES": "*Specials, Grubhub, Chownow, Slice, Doordash",
        "DEL_OPTS": "Grubhub, Chownow, Slice, Doordash",
        "Workers": 5,
        "TYPE": "Pizza",
        "WEBSITE": "https://pepzpizzamenu.com",
        "Doordash": "https://www.doordash.com/store/pepz-pizza-eatery-placentia-16441/en-US",
        "Grubhub": "https://www.grubhub.com/restaurant/pepz-pizza--eatery-732-n-rose-dr-placentia/287844",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118103.270412136,
            "y": 4012442.0285473377,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 36,
        "NAME": "EVEREST CUISINE OF INDIA",
        "ADDR": "2075 E ORANGETHORPE AVE",
        "PHONE": "(714) 993-0111",
        "DAYS": "Mon - Sun",
        "HOURS": "11 AM - 3 PM, 5 Pm 10 PM",
        "OPTIONS": "Delivery, Take-Out",
        "DISCOUNTS": "None",
        "NOTES": "*Ubereats, Doordash, Grubhub, Postmates, Free del*",
        "DEL_OPTS": "Ubereats, Doordash, Grubhub, Postmates",
        "Workers": 8,
        "TYPE": "Indian",
        "WEBSITE": "https://everestcuisineplacentia.com",
        "Doordash": "https://www.doordash.com/store/everest-cuisine-of-india-placentia-648429/en-US",
        "Grubhub": "https://www.grubhub.com/restaurant/everest-cuisine-of-india-2075-e-orangethorpe-ave-placentia/1174860",
        "Postmates": "https://postmates.com/merchant/everest-cuisine-of-india-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13115615.374400198,
            "y": 4011083.490705672,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 37,
        "NAME": "DENNY'S #7656",
        "ADDR": "108 E ORANGETHORPE AVE",
        "PHONE": "(714) 528-1661",
        "DAYS": "Sun - Thurs, Fri - Sat",
        "HOURS": "7 AM - 10 PM, FRI/SAT 7 AM - 12 AM",
        "OPTIONS": "Delivery, Take-Out",
        "DISCOUNTS": "None",
        "NOTES": "Ubereats, Doordash, Grubhub, Postmates, Free deli*",
        "DEL_OPTS": "Ubereats, Doordash, Grubhub, Postmates, Free deli*",
        "Workers": 23,
        "TYPE": "American",
        "WEBSITE": "https://dennys.com",
        "Doordash": " ",
        "Grubhub": "https://www.grubhub.com/restaurant/dennys-108-e-orangethorpe-ave-placentia/668012",
        "Postmates": "https://postmates.com/merchant/dennys-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121503.825299881,
            "y": 4010286.6979383333,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 38,
        "NAME": "BROWN BAG PLUS PIZZA MAN",
        "ADDR": "350 E ORANGETHORPE AVE",
        "PHONE": "(714) 996-5670",
        "DAYS": "Mon - Sun",
        "HOURS": "11 AM - 11 PM",
        "OPTIONS": "Delivery, Takeout",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": "Grubhub, Seamless, Slice, delivery.com,",
        "Workers": 11,
        "TYPE": "Pizza",
        "WEBSITE": "https://pizzamanplacentia.blizzfull.com",
        "Doordash": " ",
        "Grubhub": "https://www.grubhub.com/restaurant/pizza-man-350-e-orangethorpe-ave-ste-29-placentia/157146",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120623.785165453,
            "y": 4010561.694025211,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 39,
        "NAME": "EL PUEBLITO RESTAURANT, INC",
        "ADDR": "1221 E IMPERIAL HWY",
        "PHONE": "(714) 854-7956",
        "DAYS": "Sun - Thur, Fri - Sat",
        "HOURS": "Weekdays & Sun 9 AM -  9 AM, 9 AM - 7 PM",
        "OPTIONS": "Pickup, Takeout",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": " ",
        "Workers": 11,
        "TYPE": "Mexican",
        "WEBSITE": "https://el-pueblito.cafes-usa.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118003.454789553,
            "y": 4015983.700098523,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 40,
        "NAME": "BROOKLYN PIZZA WORKS & ITALIAN RESTAURANT",
        "ADDR": "1235 E IMPERIAL HWY",
        "PHONE": "(714) 524-1260",
        "DAYS": "Tues - Sun",
        "HOURS": "11 AM - 9 PM",
        "OPTIONS": "Delivery, Takeout",
        "DISCOUNTS": "$10 Meal/per person",
        "NOTES": "*Delivery & pick up specials for pizza & pasta/Co*",
        "DEL_OPTS": "Grubhub, Seamless, Postmates, Slice",
        "Workers": 11,
        "TYPE": "Pizza, Italian",
        "WEBSITE": "https://www.brooklynpizzaplacentia.com/",
        "Doordash": " ",
        "Grubhub": "https://www.grubhub.com/restaurant/brooklyn-pizza-works-1235-e-imperial-hwy-placentia/557250",
        "Postmates": "https://postmates.com/merchant/brooklyn-pizza-works-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13117969.81481402,
            "y": 4016055.7807497126,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 41,
        "NAME": "YASAI JAPANESE GRILL",
        "ADDR": "139 E YORBA LINDA BLVD",
        "PHONE": "(714) 577-8349",
        "DAYS": "Mon - Sun",
        "HOURS": "11 AM - 9 PM (hours vary)",
        "OPTIONS": "Takeout only, 3rd party Delivery",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": "Doordash",
        "Workers": 10,
        "TYPE": "Japanese",
        "WEBSITE": "https://yasaiusa.com",
        "Doordash": "https://www.doordash.com/store/yasai-japanese-grill-placentia-16498/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120650.598306773,
            "y": 4013812.239376756,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 42,
        "NAME": "WASABI SUSHI & ROLL",
        "ADDR": "1041 E IMPERIAL HWY",
        "PHONE": "(714) 223-7878",
        "DAYS": "Fri - Sun",
        "HOURS": "12 PM - 8 PM",
        "OPTIONS": "Takeout, Delivery",
        "DISCOUNTS": "None",
        "NOTES": "*Doordash",
        "DEL_OPTS": "Doordash",
        "Workers": 1,
        "TYPE": "Asian Fusion",
        "WEBSITE": " ",
        "Doordash": "https://www.doordash.com/store/wasabi-sushi-roll-placentia-448827/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13118402.813638357,
            "y": 4016226.8834075034,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 43,
        "NAME": "B & C BURGERS",
        "ADDR": "1868 N PLACENTIA AVE",
        "PHONE": "(714) 227-0477",
        "DAYS": "Mon - Sun",
        "HOURS": "8 AM - 8 PM",
        "OPTIONS": "Takeout, 3rd party Delivery",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": "Doordash",
        "Workers": 2,
        "TYPE": "Mexican",
        "WEBSITE": "https://www.bncburgers.com/",
        "Doordash": "https://www.doordash.com/store/b-c-burgers-placentia-31865/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121282.171514187,
            "y": 4014775.7417710708,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 44,
        "NAME": "MEAT UP BBQ",
        "ADDR": "1450 N KRAEMER BLVD",
        "PHONE": "(714) 983-7558",
        "DAYS": "Tue - Sun",
        "HOURS": "11 AM - 9 PM",
        "OPTIONS": "Takeout, Delivery",
        "DISCOUNTS": "FREE Delivery within 5 Miles with $50 order",
        "NOTES": "*Ubereats (Free Delivery), Doordash, Grubhub",
        "DEL_OPTS": "Ubereats, Doordash, Grubhub",
        "Workers": 3,
        "TYPE": "Barbecue",
        "WEBSITE": "https://meatupbbq.com",
        "Doordash": "https://www.doordash.com/store/meat-up-bbq-placentia-16344/en-US",
        "Grubhub": "https://www.grubhub.com/restaurant/meat-up-bbq-1450-n-kraemer-blvd-placentia/1465867",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120326.698656239,
            "y": 4013656.4313308746,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 45,
        "NAME": "SAIGON NOODLE HOUSE",
        "ADDR": "1486 N KRAEMER BLVD",
        "PHONE": "(714) 528-4087",
        "DAYS": "Mon - Sun",
        "HOURS": "3 PM - 7 PM (Mar. 18 - March 31)",
        "OPTIONS": " ",
        "DISCOUNTS": "None",
        "NOTES": "*Callback later after 3 pm",
        "DEL_OPTS": " ",
        "Workers": 4,
        "TYPE": "Vietnamese",
        "WEBSITE": " ",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120312.449413177,
            "y": 4013751.594451005,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 46,
        "NAME": "CHIPOTLE MEXICAN GRILL #3373",
        "ADDR": "1474 N KRAEMER BLVD",
        "PHONE": "(614) 318-2482",
        "DAYS": "Mon - Sun",
        "HOURS": "10:45 AM - 10 PM",
        "OPTIONS": "Takeout",
        "DISCOUNTS": "Free Delivery",
        "NOTES": "*Doordash",
        "DEL_OPTS": "Doordash, Postmates",
        "Workers": 5,
        "TYPE": "Mexican",
        "WEBSITE": "https://chipotle.com",
        "Doordash": "https://www.doordash.com/store/chipotle-placentia-742870/en-US",
        "Grubhub": " ",
        "Postmates": "https://postmates.com/merchant/chipotle-mexican-grill-placentia",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13120437.835755944,
            "y": 4013714.0116992784,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 47,
        "NAME": "TAQUERIA DE ANDA",
        "ADDR": "602 W CHAPMAN AVE",
        "PHONE": "(714) 404-6766",
        "DAYS": "Mon - Sun",
        "HOURS": "9 AM - 9 PM",
        "OPTIONS": "Takeout, Delivery",
        "DISCOUNTS": "None",
        "NOTES": "*Doordash",
        "DEL_OPTS": "Doordash",
        "Workers": 6,
        "TYPE": "Mexican",
        "WEBSITE": "https://taqueriadeanda.com",
        "Doordash": "https://www.doordash.com/store/taqueria-de-anda-placentia-357761/en-US",
        "Grubhub": " ",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13121900.60925604,
            "y": 4011768.6960266614,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 48,
        "NAME": "LITTLE CAESARS #5714",
        "ADDR": "630 W CHAPMAN AVE",
        "PHONE": "(313) 471-6000",
        "DAYS": "Sun - Thu, Fri - Sat",
        "HOURS": "10:30 AM - 10 PM, 10:30 AM - 11 PM",
        "OPTIONS": "Delivery, Takeout",
        "DISCOUNTS": "None",
        "NOTES": "*714-528-8374. Doordash",
        "DEL_OPTS": "Doordash, Postmates",
        "Workers": 7,
        "TYPE": "Pizza",
        "WEBSITE": "https://littlecaesars.com",
        "Doordash": " ",
        "Grubhub": " ",
        "Postmates": "https://postmates.com/merchant/little-caesars-pizza-placentia-1",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13122017.86691879,
            "y": 4011745.6512722974,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
    {
        "FID": 49,
        "NAME": "CITY BAGEL COMPANY",
        "ADDR": "1225 E YORBA LINDA BLVD",
        "PHONE": "(714) 572-0220",
        "DAYS": "Mon - Fri | Sat | Sun",
        "HOURS": "6 AM - 3 PM, 6:30 AM - 2PM, 6:30 AM - 1 PM",
        "OPTIONS": "Delivery, Takeout",
        "DISCOUNTS": "None",
        "NOTES": " ",
        "DEL_OPTS": "Grubhub, Doordash, Seamless",
        "Workers": 8,
        "TYPE": "Bagels",
        "WEBSITE": "https://www.citybagel.co/",
        "Doordash": "https://www.doordash.com/store/our-city-bagelry-placentia-765250/en-US",
        "Grubhub": "https://www.grubhub.com/restaurant/our-city-bagelry-1225-e-yorba-linda-blvd-placentia/555954",
        "Postmates": " ",
        "Other": " ",
        "OUTDINE": "Open",
        "SHAPE": {
            "x": -13117973.688520731,
            "y": 4013920.6422460056,
            "spatialReference": {"wkid": 102100, "latestWkid": 3857},
        },
    },
]

profiles = ["online_test", "ent_test", "kube_test"]
setup_profiles(profiles[0], profiles[1], profiles[2])


@integration_test
class TestInterpolatePoints(unittest.TestCase):
    def test_overwrite(self):
        """tests overwriting an Item layer using the context param"""
        for profile in profiles:
            # establish gis connection
            gis = GIS(profile=profile, verify_cert=False)
            print("User: ", gis.users.me.username)
            # add point layer to portal
            sdf = pd.DataFrame(data)
            fs = gis.content.import_data(sdf)
            # gather layers
            point_item = gis.content.get(fs.id)
            assert isinstance(point_item, Item)
            point_layer = point_item.layers[0]
            assert isinstance(point_layer, FeatureLayer)

            # create layer that will be overwritten
            test_id = str(datetime.datetime.now().microsecond)
            output_name = "overwrite_test_interpolate_" + test_id
            target_item = interpolate_points(
                point_layer,
                field="Workers",
                interpolate_option=5,
                output_prediction_error=True,
                classification_type="EqualArea",
                num_classes=5,
                output_name=output_name,
            )
            assert isinstance(target_item, Item)
            target_layer = target_item.layers[0]
            assert isinstance(target_layer, FeatureLayer)

            # perform overwrite
            overwrite = interpolate_points(
                point_layer,
                field="Workers",
                interpolate_option=5,
                output_prediction_error=True,
                classification_type="EqualArea",
                num_classes=5,
                output_name=target_layer,
                context={"overwrite": True},
            )
            assert isinstance(overwrite, Item)
            assert target_item.id == overwrite.id
            # overwrite should not append. Only one layer should be present
            assert len(target_item.layers) == 2

            # delete items that were added for test purpose
            assert target_item.delete()
            assert fs.delete()


if __name__ == "__main__":
    unittest.main()
