from automation._classes.HtmlFileTestSuite import HtmlFileTestSuite
from automation._classes.HtmlImgLinkParser import HtmlImgLinkParser
from automation._classes.TestHtmlMatch import TestHtmlMatch
from automation._classes.TestNotebook.TestNotebook import TestNotebook
