# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: esriPBuffer/EsriExtendedTypes/EsriExtendedTypes.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b"\n5esriPBuffer/EsriExtendedTypes/EsriExtendedTypes.proto\x12\x1d\x65sriPBuffer.EsriExtendedTypes*\xe3\x03\n\tFieldType\x12\x1d\n\x19\x65sriFieldType_UNSPECIFIED\x10\x00\x12\x1d\n\x19\x65sriFieldTypeSmallInteger\x10\x01\x12\x18\n\x14\x65sriFieldTypeInteger\x10\x02\x12\x17\n\x13\x65sriFieldTypeSingle\x10\x03\x12\x17\n\x13\x65sriFieldTypeDouble\x10\x04\x12\x17\n\x13\x65sriFieldTypeString\x10\x05\x12\x15\n\x11\x65sriFieldTypeDate\x10\x06\x12\x14\n\x10\x65sriFieldTypeOID\x10\x07\x12\x19\n\x15\x65sriFieldTypeGeometry\x10\x08\x12\x15\n\x11\x65sriFieldTypeBlob\x10\t\x12\x17\n\x13\x65sriFieldTypeRaster\x10\n\x12\x15\n\x11\x65sriFieldTypeGUID\x10\x0b\x12\x19\n\x15\x65sriFieldTypeGlobalID\x10\x0c\x12\x14\n\x10\x65sriFieldTypeXML\x10\r\x12\x1b\n\x17\x65sriFieldTypeBigInteger\x10\x0e\x12\x19\n\x15\x65sriFieldTypeDateOnly\x10\x0f\x12\x19\n\x15\x65sriFieldTypeTimeOnly\x10\x10\x12 \n\x1c\x65sriFieldTypeTimestampOffset\x10\x11\x42-\n&com.esri.arcgis.protobuf.extendedtypesH\x03\xf8\x01\x01\x62\x06proto3"
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(
    DESCRIPTOR, "esriPBuffer.EsriExtendedTypes.EsriExtendedTypes_pb2", globals()
)
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = (
        b"\n&com.esri.arcgis.protobuf.extendedtypesH\003\370\001\001"
    )
    _FIELDTYPE._serialized_start = 89
    _FIELDTYPE._serialized_end = 572
# @@protoc_insertion_point(module_scope)
