import types
import typing
import datetime
import pandas as pd

from arcgis.features import SpatialDataFrame, FeatureLayer #
from arcgis.features.layer import FeatureLayerCollection #
from arcgis.geocoding import Geocoder
from arcgis.geoprocessing._tool import Toolbox #

from arcgis.network import NetworkDataset #
from arcgis.gis import Layer
from arcgis.mapping import VectorTileLayer
from arcgis.mapping import MapImageLayer #
from arcgis.raster import ImageryLayer
from arcgis.schematics import SchematicLayers
from arcgis.mapping._types import SceneLayer

_mapping = {
    'Address Locator': 'DEAddressLocator',
    'Address Locator Style': 'GPAddressLocatorStyle',
    #'Analysis Cell Size': 'analysis_cell_size',
    'Any Value': 'GPType',
    'ArcMap Document': 'DEMapDocument',
    'Areal Unit': 'GPArealUnit',
    'Boolean': 'GPBoolean',
    'bool' : "GPBoolean",
    bool : "GPBoolean",
    'CAD Drawing Dataset': 'DECadDrawingDataset',
    'Calculator Expression': 'GPCalculatorExpression',
    'Catalog Root': 'DECatalogRoot',
    'Cell Size': 'GPSACellSize',
    'Cell Size XY': 'GPCellSizeXY',
    'Composite Layer': 'GPCompositeLayer',
    'Compression': 'GPSAGDBEnvCompression',
    'Coordinate System': 'GPCoordinateSystem',
    'Coordinate Systems Folder': 'DESpatialReferencesFolder',
    'Coverage': 'DECoverage',
    'Coverage Feature Class': 'DECoverageFeatureClasses',
    'Data Element': 'DEType',
    'Data File': 'GPDataFile',
    'Database Connections': 'DERemoteDatabaseFolder',
    'Dataset': 'DEDatasetType',
    'Date': 'GPDate',
    datetime.datetime : "GPDate",
    'datetime.datetime' : "GPDate",
    'datetime' : "GPDate",
    'dBASE Table': 'DEDbaseTable',
    'Decimate': 'GP3DADecimate',
    'Diagram Layer': 'GPDiagramLayer',
    'Disk Connection': 'DEDiskConnection',
    'Double': 'GPDouble',
    float : "GPDouble",
    'float' : "GPDouble",
    'Encrypted String': 'GPEncryptedString',
    'Envelope': 'GPEnvelope',
    'Evaluation Scale': 'GPEvaluationScale',
    'Extent': 'GPExtent',
    'Extract Values': 'GPSAExtractValues',
    'Feature Class': 'DEFeatureClass',
    'Feature Dataset': 'DEFeatureDataset',
    'Feature Layer': 'GPFeatureLayer',
    FeatureLayer : "GPFeatureLayer",
    'Feature Set': 'GPFeatureRecordSetLayer',
    SpatialDataFrame : "GPFeatureLayer",
    'SpatialDataFrame' : "GPFeatureLayer",
    'Field': 'Field',
    'Field Info': 'GPFieldInfo',
    'Field Mappings': 'GPFieldMapping',
    'File': 'DEFile',
    'Folder': 'DEFolder',
    'Formulated Raster': 'GPRasterFormulated',
    'Fuzzy function': 'GPSAFuzzyFunction',
    'Geodataset': 'DEGeodatasetType',
    'GeoDataServer': 'DEGeoDataServer',
    'Geometric Network': 'DEGeometricNetwork',
    'Geostatistical Layer': 'GPGALayer',
    'Geostatistical Search Neighborhood': 'GPGASearchNeighborhood',
    'Geostatistical Value Table': 'GPGAValueTable',
    'GlobeServer': 'DEGlobeServer',
    'GPServer': 'DEGPServer',
    Toolbox : "DEGPServer",
    'Toolbox' : "DEGPServer",
    'Graph': 'GPGraph',
    'Graph Data Table': 'GPGraphDataTable',
    'Group Layer': 'GPGroupLayer',
    'Horizontal Factor': 'GPSAHorizontalFactor',
    'Image Service': 'DEImageServer',
    'Index': 'Index',
    int : "GPLong",
    'int' : "GPLong",
    'INFO Expression': 'GPINFOExpression',
    'INFO Item': 'GPArcInfoItem',
    'INFO Table': 'DEArcInfoTable',
    'Internet Tiled Layer': 'GPInternetTiledLayer',
    'KML Layer': 'GPKMLLayer',
    'LAS Dataset': 'DELasDataset',
    'LAS Dataset Layer': 'GPLasDatasetLayer',
    'Layer': 'GPLayer',
    'Layer File': 'DELayer',
    'Line': 'GPLine',
    'Linear Unit': 'GPLinearUnit',
    'Long': 'GPLong',
    'M Domain': 'GPMDomain',
    'Map': 'GPMap',
    'MapServer': 'DEMapServer',
    'Map Server Layer': 'GPMapServerLayer',
    MapImageLayer : 'GPMapServerLayer',
    'MapImageLayer' : 'GPMapServerLayer',
    'Mosaic Dataset': 'DEMosaicDataset',
    'Mosaic Layer': 'GPMosaicLayer',
    'Neighborhood': 'GPSANeighborhood',
    'Network Analyst Class FieldMap': 'NAClassFieldMap',
    'Network Analyst Hierarchy Settings': 'GPNAHierarchySettings',
    'Network Analyst Layer': 'GPNALayer',
    NetworkDataset : 'GPNetworkDatasetLayer',
    'NetworkDataset' : 'GPNetworkDatasetLayer',
    'Network Dataset': 'DENetworkDataset',
    'Network Dataset Layer': 'GPNetworkDatasetLayer',
    'Network Travel Mode': 'NetworkTravelMode',
    'Parcel Fabric For ArcMap': 'DECadastralFabric',
    'Parcel Fabric Layer': 'GPCadastralFabricLayer',
    'Point': 'GPPoint',
    'Polygon': 'GPPolygon',
    'Projection File': 'DEPrjFile',
    'Pyramid': 'GPSAGDBEnvPyramid',
    'Radius': 'GPSARadius',
    'Random Number Generator': 'GPRandomNumberGenerator',
    'Raster Band': 'DERasterBand',
    'Raster Calculator Expression': 'GPRasterCalculatorExpression',
    'Raster Catalog': 'DERasterCatalog',
    'Raster Catalog Layer': 'GPRasterCatalogLayer',
    'Raster Data Layer': 'GPRasterDataLayer',
    'Raster Dataset': 'DERasterDataset',
    'Raster Layer': 'GPRasterLayer',
    ImageryLayer : "GPRasterLayer",
    'Raster Statistics': 'GPSAGDBEnvStatistics',
    'Raster Type': 'GPRasterBuilder',
    'Record Set': 'GPRecordSet',
    pd.DataFrame : "GPRecordSet",
    'Relationship Class': 'DERelationshipClass',
    'Remap': 'GPSARemap',
    'Route Measure Event Properties': 'GPRouteMeasureEventProperties',
    'Scene Service Layer': 'GPSceneServiceLayer',
    SceneLayer : 'GPSceneServiceLayer',
    'Schematic Dataset': 'DESchematicDataset',
    'Schematic Diagram': 'DESchematicDiagram',
    'Schematic Diagram Class': 'DESchematicDiagramClass',
    'Schematic Folder': 'DESchematicFolder',
    'Schematic Layer': 'GPSchematicLayer',
    SchematicLayers : 'GPSchematicLayer',
    'SemiVariogram': 'GPSASemiVariogram',
    'ServerConnection': 'DEServerConnection',
    'Shapefile': 'DEShapefile',
    'Spatial Reference': 'GPSpatialReference',
    'SQL Expression': 'GPSQLExpression',
    'String': 'GPString',
    str : "GPString",
    'str' : "GPString",
    'String Hidden': 'GPStringHidden',
    'Table': 'DETable',
    'Table View': 'GPTableView',
    'Terrain Layer': 'GPTerrainLayer',
    'Text File': 'DETextfile',
    'Tile Size': 'GPSAGDBEnvTileSize',
    'Time configuration': 'GPSATimeConfiguration',
    'Time Unit': 'GPTimeUnit',
    'TIN': 'DETin',
    'Tin Layer': 'GPTinLayer',
    'Tool': 'DETool',
    'Toolbox': 'DEToolbox',
    'Topo Features': 'GPSATopoFeatures',
    'Topology': 'DETopology',
    'Topology Layer': 'GPTopologyLayer',
    'Transformation Function': 'GPSATransformationFunction',
    'Utility Network': 'GPUtilityNetwork',
    'Utility Network Layer': 'GPUtilityNetworkLayer',
    'Value Table': 'GPValueTable',
    'Variant': 'GPVariant',
    'Vector Tile Layer': 'GPVectorLayer',
    VectorTileLayer : "GPVectorLayer",
    'Vertical Factor': 'GPSAVerticalFactor',
    'VPF Coverage': 'DEVPFCoverage',
    'VPF Table': 'DEVPFTable',
    'WCS Coverage': 'DEWCSCoverage',
    'Weighted Overlay Table': 'GPSAWeightedOverlayTable',
    'Weighted Sum': 'GPSAWeightedSum',
    'WMS Map': 'DEWMSMap',
    'Workspace': 'DEWorkspace',
    'XY Domain': 'GPXYDomain',
    'Z Domain': 'GPZDomain'
}

try:
    import arcpy
    _mapping[arcpy.RecordSet] = 'GPRecordSet'
    _mapping['RecordSet'] = 'GPRecordSet'
    _mapping[arcpy.FeatureSet] = "GPFeatureRecordSetLayer"
    _mapping['FeatureSet'] = "GPFeatureRecordSetLayer"
except: pass
