[unittest]
owner=kevin
team=geosaurus

[arcgiscom]
url=https://www.arcgis.com
admin_user=USERNAME
admin_pass=PASSWORD

[localportal1]
; some local portal
url=http://localportal:6080
admin_user=bob
admin_pass=123


[localportal2]
; some local portal
url=http://localportal:6080
admin_user=bob
admin_pass=123