# This file created by conda-build 2.0.1
# meta.yaml template originally from:
# e:\share\conda-project\conda-packages\arcgis-api, last modified Mon Sep 19 14:51:09 2016
# ------------------------------------------------

package:
    name: arcgis
    version: '0.3'
source:
    fn: geosaurus-0.3-prerel.zip
    sha256: 53affcf14819c048475af579d4da43f0eb007bc5fd779533e877e441e889cdf9
    url: http://pydemo.esri.com:9000/geosaurus-0.3-prerel.zip
build:
    number: '1'
requirements:
    build:
        - python
        - setuptools
        - six
        - ipywidgets >=5.2.2
        - widgetsnbextension >=1.2.6
        - pywin32
        - kerberos-sspi
    run:
        - python
        - six
        - ipywidgets >=5.2.2
        - widgetsnbextension >=1.2.6
        - pywin32
        - kerberos-sspi
test:
    imports:
        - arcgis
        - arcgis.viz
about:
    home: https://developers.arcgis.com/python
    license: Esri License
    summary: ArcGIS Python API (Pre-release)
