name: arcgis-learn-api-confidence-tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'src/arcgis/learn/**'
      - 'tests/integration/arcgis_learn/**'

permissions:
  contents: read
  pull-requests: read

jobs:
  trigger-pull_request:
    runs-on: self-hosted

    steps:
      - name: Checkout PR code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: run tests in conda env
        run: |
          PYTHON=/root/anaconda3/envs/jenkins_03_April_25/bin/python
          echo "Python Version:"
          $PYTHON --version

          echo "Working directory"
          pwd

          echo "Setting up required environment variables"
          WORKSPACE=pwd
          export LC_ALL=en_US.UTF-8; export LC_CTYPE=en_US.UTF-8;
          export run_nightly=0; export run_inference=0; export run_weekly=0; export run_backbones=0;
          export PYTHONPATH="$WORKSPACE/tests"
          SMOKE_DIR="$WORKSPACE/tests/smoke"

          echo "Running smoke tests from: $SMOKE_DIR"
          echo "======================================="
          for test_file in "$SMOKE_DIR"/*.py; do
            $PYTHON "$test_file"
            exit_code=$?
          
          echo "All smoke tests passed."
          echo "======================================="
          
