name: Python Package using Conda

on: [workflow_dispatch]

jobs:
  build-linux:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
         os: [ubuntu-latest]
         python-version: ['3.7']
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Update Build YAML file
      uses: fjogeleit/yaml-update-action@master
      with:
        valueFile: 'build/esri_requests/meta.yaml'
        propertyPath: 'build.number'
        value: "${{ github.run_number }}"
        commitChange: false
        updateFile: true
    - name: Read Build YAML
      id: package
      uses: juliangruber/read-file-action@v1
      with:
        path: 'build/esri_requests/meta.yaml'
    - name: Echo meta.yaml
      run: echo "${{ steps.package.outputs.content }}"
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies using Miniconda
      run: |
        conda env update --file environment.yml --name base
    - name: Install Conda-Build
      run: |
        cd ./build
        mkdir output_build
        conda install conda-build
        conda update conda
        conda update conda-build
        conda build --croot ./output_build -c esri -c Esri-build esri_requests
    - name: check folder
      run: |
        cd ./build/output_build
        ls
    - uses: actions/upload-artifact@v2  
      with:
        name: conda-build-${{ matrix.os }}-${{matrix.python-version}}-${{ github.sha }}
        path: build/output_build/**/*.tar.bz2
        retention-days: 10
