name: Build Python Packages
on: workflow_dispatch

env:
  BUILD_NUMBER: ${{ github.run_number }}

jobs:
  build-pip:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v4
      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          channels: conda-forge
          conda-remove-defaults: true
          environment-file: build.environment.yml
      - name: Configure conda
        run: |
          conda remove -n base conda-anaconda-telemetry -y && echo "conda-anaconda-telemetry removed..." || echo "conda-anaconda-telemetry not installed..."
      - name: Stage binary dependencies
        run: |
          python ./build/manage_binaries.py copy
      - name: Build wheel
        run: |
          cd ./src; 
          python -m build --wheel --outdir dist .
      - name: Build sdist
        run: |
          cd ./src; 
          python -m build --sdist --outdir dist .
      - name: Upload pacakges
        uses: actions/upload-artifact@v4
        with:
          name: arcgis-pypi-build-${{ github.run_number }}-${{ github.sha }}
          path: |
            src/dist/**/*.whl
            src/dist/**/*.tar.gz
          retention-days: 90
