name: Documentation
on:
  workflow_dispatch:
  pull_request:
  workflow_run:
    workflows: [Build]
    types:
    - completed

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout geosaurus
        with:
          path: geosaurus
      - uses: actions/checkout@v4
        name: Checkout arcgis-mapping
        if: github.repository == 'ArcGIS/geosaurus'
        with:
          repository: ArcGIS/geoserpent
          path: geoserpent
          token: ${{ secrets.GH_GEOSERPENT_TOKEN }}
      - if: github.repository != 'ArcGIS/geosaurus'
        name: Mock arcgis-mapping for forks
        run: |
          mkdir -p geoserpent/arcgis-mapping/src/arcgis/map
          touch geoserpent/arcgis-mapping/src/arcgis/map/__init__.py
          echo "::warning title=Mocked arcgis-mapping::doc build will not include arcgis-mapping content"
      - uses: prefix-dev/setup-pixi@v0.8.10
        with:
          pixi-version: v0.48.2
          manifest-path: geosaurus/pixi.toml
          environments: >-
            docs
            awscli
          frozen: true
      - run: |
            cd geosaurus && pixi run docs
      - uses: actions/upload-artifact@v4
        with:
          name: arcgis-docs-html-${{ github.run_number }}-${{ github.sha }}
          path: geosaurus/docs/api_ref/build/html
      - uses: actions/upload-artifact@v4
        with:
          name: arcgis-docs-json-${{ github.run_number }}-${{ github.sha }}
          path: geosaurus/docs/api_ref/build/json
      - name: Deploy doc to s3
      # https://esri-forge.python.geocloud.com/docs/$ARCGIS_DOCS_LABEL/json.zip
      # https://esri-forge.python.geocloud.com/docs/$ARCGIS_DOCS_LABEL/html.zip
        env:
          # label:
          # - branch name for docs built for successful builds or manually triggered workflows
          # - pr/<number> for docs built for pull requests
          ARCGIS_DOCS_LABEL: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.head_branch || github.event_name == 'pull_request' && format('pr/{0}', github.event.pull_request.number) || github.ref_name }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_ESRI_FORGE }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ESRI_FORGE }}
          AWS_REGION: ${{ secrets.AWS_REGION_ESRI_FORGE }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION_ESRI_FORGE }}
        run: |
            cd geosaurus
            pixi run docs:deploy:json build/${{ github.sha }}
            pixi run docs:deploy:html build/${{ github.sha }}
            pixi run docs:deploy:json $ARCGIS_DOCS_LABEL
            pixi run docs:deploy:html $ARCGIS_DOCS_LABEL