name: Check code formatting
on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  black-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/checkout@v4
        if: github.event_name == 'workflow_dispatch'
      - uses: psf/black@stable
        with:
          options: --check --verbose
          src: ./src