# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Python Wheels
on: workflow_dispatch
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.7', '3.8', '3.9']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python --version
      - name: Install libkrb5 for Kerberos on Linux
        if: contains(matrix.os, 'ubuntu')
        run: |
          echo "Test"
          sudo apt install -y libkrb5-dev
          pip install requests-kerberos
          echo "Test Ended"

      - name: Install the Requirements
        run: pip install -r src/requirements.txt
      - name: Clean PYD/SO Files and Folders
        run: |
          python ./build/clean_up_so_pyd.py "./src"      
      - name: Create the Wheels
        run: |
          cd ./src; 
          pip install wheel
          python setup.py bdist_wheel
      - uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.os }}-${{matrix.python-version}}-${{ github.sha }}
          path: src/dist/*.whl
          retention-days: 10
