name: Unit Test
on:
  pull_request:
  schedule:
    # Mondays at 12:30 PM UTC (4:30 AM Pacific/7:30 AM Eastern) (all platforms, all python versions)
    - cron: '30 12 * * 1'
    # Tuesday-Sunday at 12:30 PM UTC (Windows & Linux, Python 3.13)(Default supported platforms for ArcGIS Pro/Enterprise)
    - cron: '30 12 * * 0,2-6'
  workflow_dispatch:
    inputs:
      linux:
        type: boolean
        description: Run unit tests on Linux?
        required: false
        default: true
      macos:
        type: boolean
        description: Run unit tests on macOS?
        required: false
        default: false
      windows:
        type: boolean
        description: Run unit tests on Windows?
        required: false
        default: false
      py310:
        type: boolean
        description: Run unit tests on Python 3.10?
        required: false
        default: false
      py311:
        type: boolean
        description: Run unit tests on Python 3.11?
        required: false
        default: false
      py312:
        type: boolean
        description: Run unit tests on Python 3.12?
        required: false
        default: false
      py313:
        type: boolean
        description: Run unit tests on Python 3.13?
        required: false
        default: true

jobs:
  preflight:
    name: Run test preflight configuration
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: tj-actions/changed-files@v46
        id: changed-files
        if: github.event_name == 'pull_request'
        with:
          files: |
            environment.yml  
            pixi.toml
            pixi.lock
            .github/workflows/unit-test.yaml
            build/manage_binaries.py
      - name: Get parameters or defaults
        id: get-parameters
        # defaults to running linux and python 3.13 on most pull requests
        # defaults to running on all platforms and python versions on pull requests where certain key files were changed
        # defaults to running all platforms and python versions on Monday schedule
        # uses inputs to determine which platforms and python versions to run on for workflow_dispatch
        run: |
          echo "linux=${{ github.event_name == 'schedule' || github.event_name == 'pull_request' || github.event.inputs.linux }}" >> $GITHUB_OUTPUT
          echo "macos=${{ (github.event_name == 'schedule' && github.event.schedule == '30 12 * * 1') || (github.event_name == 'pull_request' && steps.changed-files.outputs.any_changed == 'true') || github.event.inputs.macos }}" >> $GITHUB_OUTPUT
          echo "windows=${{ github.event_name == 'schedule' || (github.event_name == 'pull_request' && steps.changed-files.outputs.any_changed == 'true') || github.event.inputs.windows }}" >> $GITHUB_OUTPUT
          echo "py310=${{ (github.event_name == 'schedule' && github.event.schedule == '30 12 * * 1') || (github.event_name == 'pull_request' && steps.changed-files.outputs.any_changed == 'true') || github.event.inputs.py310 }}" >> $GITHUB_OUTPUT
          echo "py311=${{ (github.event_name == 'schedule' && github.event.schedule == '30 12 * * 1') || (github.event_name == 'pull_request' && steps.changed-files.outputs.any_changed == 'true') || github.event.inputs.py311 }}" >> $GITHUB_OUTPUT
          echo "py312=${{ (github.event_name == 'schedule' && github.event.schedule == '30 12 * * 1') || (github.event_name == 'pull_request' && steps.changed-files.outputs.any_changed == 'true') || github.event.inputs.py312 }}" >> $GITHUB_OUTPUT
          echo "py313=${{ github.event_name == 'schedule' || github.event_name == 'pull_request' || github.event.inputs.py313 }}" >> $GITHUB_OUTPUT
      - name: Construct matrix
        id: set-matrix
        run: |
          matrix=$(echo {} | jq '. |= {"os": [], "python_version": []}' | jq -r tostring)
          if [ "${{ steps.get-parameters.outputs.linux }}" = 'true' ]; then
            echo "Running on Linux"
            matrix=$(echo $matrix | jq '.os += ["ubuntu-latest"]' | jq -r tostring)
          fi
          if [ "${{ steps.get-parameters.outputs.macos }}" = 'true' ]; then
            echo "Running on macOS"
            matrix=$(echo $matrix | jq '.os += ["macos-latest"]' | jq -r tostring)
          fi
          if [ "${{ steps.get-parameters.outputs.windows }}" = 'true' ]; then
            echo "Running on Windows"
            matrix=$(echo $matrix | jq '.os += ["windows-latest"]' | jq -r tostring)
          fi
          if [ "${{ steps.get-parameters.outputs.py310 }}" = 'true' ]; then
            echo "Running on Python 3.10"
            matrix=$(echo $matrix | jq '.python_version += ["3.10"]' | jq -r tostring)
          fi
          if [ "${{ steps.get-parameters.outputs.py311 }}" = 'true' ]; then
            echo "Running on Python 3.11"
            matrix=$(echo $matrix | jq '.python_version += ["3.11"]' | jq -r tostring)
          fi
          if [ "${{ steps.get-parameters.outputs.py312 }}" = 'true' ]; then
            echo "Running on Python 3.12"
            matrix=$(echo $matrix | jq '.python_version += ["3.12"]' | jq -r tostring)
          fi
          if [ "${{ steps.get-parameters.outputs.py313 }}" = 'true' ]; then
            echo "Running on Python 3.13"
            matrix=$(echo $matrix | jq '.python_version += ["3.13"]' | jq -r tostring)
          fi
          echo "matrix=$matrix" >> $GITHUB_OUTPUT
  unit-test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    needs: [preflight]
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.preflight.outputs.matrix)}}
    defaults:
      run:
        shell: bash -el {0}
    env:
      ALLOW_INSTALLED_ARCGIS: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Checkout code
        uses: actions/checkout@v4
        if: github.event_name != 'pull_request'
      - name: Configure python
        run: |
          python -m pip install pyyaml
      - name: Preprocess environment.yml
        run: |
          import re, yaml
          with open('environment.yml', 'r') as env_file:
              env = yaml.safe_load(env_file)
          is_python = lambda dep: type(dep) is str and re.split('=|==|<=|>=| |,|!=|~', dep)[0] == 'python'
          env['dependencies'] = [dep for dep in env['dependencies'] if not is_python(dep)]
          with open('environment.yml', 'w') as env_file:
              yaml.safe_dump(env, env_file)
        shell: python
      - name: Print environment.yml
        run: |
          cat environment.yml
      - name: Configure conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python_version }}
          environment-file: environment.yml
          auto-update-conda: true
      - name: Get conda environment path
        id: conda-info
        run: |
          echo "conda-env-path=$CONDA_PREFIX" >> $GITHUB_OUTPUT
      - name: Load dependency cache
        id: restore-cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ steps.conda-info.outputs.conda-env-path }}
          key: conda-arcgis-${{ matrix.os }}-py${{ matrix.python_version }}-${{ hashFiles('.github/workflows/unit-test.yaml', 'environment.yml', 'build/arcgis/meta.yaml', 'src/requirements.txt', 'src/setup.py') }}
      - name: Save dependency cache
        id: save-cache
        if: steps.restore-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: ${{ steps.conda-info.outputs.conda-env-path }}
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}
      - name: Show conda environment
        run: |
          conda list
          conda info
      - name: Copy binary dependencies
        run: |
          python build/manage_binaries.py copy --local
      - name: Install arcgis from source
        run: |
          python -m pip install ./src --no-deps
      - name: Run smoke tests
        working-directory: ./tests
        run: |
          python -m nose2 -s smoke --plugin nose2.plugins.junitxml --junit-xml --junit-xml-path=smoke_py${{ matrix.python_version }}_${{ runner.os }}_testreport.xml
        env:
          TEST_ARCGIS_LEARN: false
      - name: Run unit tests
        working-directory: ./tests
        run: |
          python -m nose2 -s unit --plugin nose2.plugins.junitxml --junit-xml --junit-xml-path=unit_py${{ matrix.python_version }}_${{ runner.os }}_testreport.xml
        # always run unit tests, except for cancellation
        if: success() || failure()
      - name: Upload test report
        uses: actions/upload-artifact@v4
        with:
          name: test-results-py${{ matrix.python_version }}-${{ matrix.os }}
          path: ./tests/*_testreport.xml
          if-no-files-found: ignore
          retention-days: 30
        # always upload test results, except for cancellation
        if: success() || failure()

  report:
    name: Publish test reports
    needs: [unit-test]
    if: success() || failure()
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - name: Download test reports
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Aggregate test reports
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: ./*_testreport.xml
          if-no-files-found: ignore
      - name: Publish test reports
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: "*_testreport.xml"