name: Unit Test
on:
  pull_request: {}
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    env:
      ARCGIS_LAST_RELEASE: 2.2.0
    steps:
      - uses: actions/checkout@v4
        if: github.event_name == 'pull_request'
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/checkout@v4
        if: github.event_name == 'workflow_dispatch'
      - uses: actions/checkout@v4
        with:
          ref: binaries/main
          path: binaries
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: 3.9
      - name: Get conda environment path
        id: conda-info
        run: |
          echo "conda-env-path=$CONDA_PREFIX" >> $GITHUB_OUTPUT
      - name: Load Cache
        id: restore-cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ steps.conda-info.outputs.conda-env-path }}
          key: conda-${{ runner.os }}-arcgis${{ env.ARCGIS_LAST_RELEASE }}-${{ hashFiles('.github/workflows/unit-test.yaml', 'environment.yml', 'build/arcgis/meta.yaml', 'src/requirements.txt', 'src/setup.py') }}
          restore-keys: |
            conda-${{ runner.os }}-arcgis${{ env.ARCGIS_LAST_RELEASE }}-
      - name: Install dependencies
        run: |
          conda install -c main nose2 --yes
          conda install -c esri arcgis=${{ env.ARCGIS_LAST_RELEASE }}.* --only-deps --yes
          conda install -c esri-build pydantic --yes
          conda install -c esri-build puremagic --yes
          conda install -c main "pyarrow>=11" --yes
        if: steps.restore-cache.outputs.cache-hit != 'true'
      - name: Save Cache
        id: save-cache
        uses: actions/cache/save@v3
        with:
          path: ${{ steps.conda-info.outputs.conda-env-path }}
          key: ${{ steps.restore-cache.outputs.cache-primary-key }}
        if: steps.restore-cache.outputs.cache-hit != 'true'
      - name: Install arcgis
        run: |
          # copy binaries to relevant paths
          cp ./binaries/linux/py3.9/graph/* ./src/arcgis/graph
          cp ./binaries/linux/py3.9/knn/* ./src/arcgis/learn/_utils
          cp ./binaries/linux/py3.9/tracking-engine/* ./src/arcgis/learn/_tracking

          python -m pip install -e ./src --no-deps
      - name: Run smoke tests
        working-directory: ./tests
        run: |
          python -m nose2 -s smoke
        env:
          TEST_ARCGIS_LEARN: false
      - name: Run unit tests
        working-directory: ./tests
        run: |
          python -m nose2 -s unit
        # run unit tests even if smoke tests fail
        if: success() || failure()